### ISSUE TITLE
`asprof` produces malformed html file

### ISSUE THREAD

**Issue by SergeevPavel** [async-profiler/async-profiler#1000]
### Describe the bug

I'm using `asprof` to profile [Fleet](https://www.jetbrains.com/fleet/) .
The command is following: `sudo ./asprof -d 5 -e cpu -i 1ms  (pgrep Fleet) -f result.html`
It produces the following result: 
[result.zip](https://github.com/user-attachments/files/17028915/result.zip)

When I'm trying to open it in browser I get:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at f (result.html:69:26)
    at n (result.html:80:3)
    at result.html:4166:1
```
I have a strong feeling that the cause is incorrectly generated html file, namely, I expect array size here:
```
	const levels = Array();
	for (let h = 0; h < levels.length; h++) {
		levels[h] = [];
	}
```
instead of empty brackets.

### Expected vs. actual behavior

I expected to get an html flame graph, that would be able to view in browser.

### Reproduction Steps

1. Run Fleet
2. Generate report `sudo ./asprof -d 5 -e cpu -i 1ms  (pgrep Fleet) -f result.html`
3. Try to open `result.html` in Chrome browser

### Additional Information/Context

* I've tried on macOS and it's working
* With `-o tree` it produces expected result
* text output is also fine 

### Async-profiler version

Async-profiler 3.0 built on Jan 20 2024

### Environment details

Linux 6.5.13-7-MANJARO
Java vendor: JetBrains s.r.o.
Java version: 21.0.3+13-b509.4

**Comment by krk** [comment]
Height is missing too, which is calculated from the same source, `depth` in https://github.com/async-profiler/async-profiler/blob/6d7f73aec1c63d6ad140df717a7fabbb4ce5c764/src/flameGraph.cpp#L144-L145 and rendered into https://github.com/async-profiler/async-profiler/blob/6d7f73aec1c63d6ad140df717a7fabbb4ce5c764/src/res/flame.html#L17



```
#canvas {width: 100%; height: px}
```

**Comment by apangin** [comment]
That's a peculiarity of the standard c++ library's `ofstream`. For some reason, it does not print numbers - perhaps, due to weird locale settings.

Fortunately, we've got rid of `ofstream` in #872. I believe the bug has been already fixed.
Please try the latest version from master. For your convenience, there are [nightly builds](https://github.com/async-profiler/async-profiler/releases/tag/nightly) available.

**Comment by SergeevPavel** [comment]
Yes, indeed it works in nightly build! Thanks for help! Looking forward for the release containing this fix.

**Comment by apangin** [comment]
Thanks for confirming.
