### ISSUE TITLE
An option to display instruction addresses

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#1001]
### Describe the feature

Add an option to show instruction address (PC) of the topmost method in a stack trace.

### Use Case

Currently, async-profiler displays information on the method/function level. Sometimes, for low-level performance analysis, it is important to know where exactly CPU time is spent inside a method.

### Proposed Solution

As an intermediate step to the instruction-level profiling, we will add an option to record PC address of the currently running method for each execution sample. In this case, each stack trace will include a synthetic frame with the address at the top of every stack trace.

The option is `-F pcaddr` (or `features=pcaddr` when running as an agent).

Example:
```
asprof -e cpu -f profile.html --cstack dwarf -F pcaddr PID
```

<img width="943" alt="pcaddr" src="https://github.com/user-attachments/assets/f5be8b3f-fbf6-4ffa-9fd9-04e4f4395635">

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by apangin** [comment]
Implemented in [pcaddr](https://github.com/async-profiler/async-profiler/tree/pcaddr) branch.

**Comment by franz1981** [comment]
Together with --lines it would be very interesting to try it!

**Comment by franz1981** [comment]
And decoding the assembly address with the actual instruction performed in some format (at&t, intel, ...). Due to skidding it won't be that relevant, but using PEBS/IBS it could be still be useful (thinking about simd instr or some unexpected call...)

**Comment by apangin** [comment]
Yes, disassembling code around these addresses will be the next step. Not in the nearest release, though.

**Comment by franz1981** [comment]
Thanks @apangin 🙏 it has passed a long time since we talked about this, and you didn't forgotten
