### ISSUE TITLE
Cache parsed arguments to reduce allocations

### ISSUE THREAD

**Issue by zz85** [async-profiler/async-profiler#1024]
### Describe the feature

C API `asprof_execute()` parses the argument string each time it's called https://github.com/async-profiler/async-profiler/blob/4ee2a5df3980f0b547d5ed29bfde5f7e89d7614a/src/asprof.cpp#L26

### Use Case

for workflows that starts and stops the profiler, it would mean the Arguments needs to be reparsed again. it'd be nice if there's an api which uses the last parsed arguments when starting.

### Proposed Solution

perhaps create an optional asprof_start(optional_args)

```
asprof_start(args); // parses the first time and memorizes parsed args as `_args`
asprof_start("") ; // use the last parsed arguments
asprof_start(new_args); // reparse and cache
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by apangin** [comment]
Thank you for your proposal. I'm interested to know what the original problem was. In general, parsing is pretty lightweight, and start/stop happens no more than once a minute, so this is not an issue even for latency sensitive applications.

**Comment by apangin** [comment]
For the reasons mentioned above, let me close the issue as not planned.
Feel free to reopen if have arguments why the change is required.

**Comment by zz85** [comment]
thanks @apangin - it was more of a proposal to mimic the cpp api's from the C interface, but the string parsing approach could be suffice for now.
