### ISSUE TITLE
Support evaluating the same PMU metrics as perf

### ISSUE THREAD

**Issue by farnoy** [async-profiler/async-profiler#1025]
### Describe the feature

perf supports calculated metrics, [like these](https://github.com/torvalds/linux/blob/36c254515dc6592c44db77b84908358979dd6b50/tools/perf/pmu-events/arch/x86/amdzen1/recommended.json#L40). It would be useful to do `-e metric=all_l2_cache_misses` with async-profiler.

### Use Case

As PMUs are getting more complex, individual events tend to be less useful

### Proposed Solution

The two big challenges probably are:

1. Adding an (optional) dependency on perf at runtime and parsing its formulas (eg. `perf list -j`)
2. Multiplexing collection of many events that are needed for a given metric - PMUs can only collect a fixed number simultaneously

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by apangin** [comment]
Thank you for your proposal!
Being a very niche feature, it is unlikely to appear on our roadmap in the nearest future, however, we are happy to review a pull request if you wish to contribute.

**Comment by apangin** [comment]
I'm closing the issue due to inactivity. We have no plans to implement this feature right now, but we may reconsider this in the future, if there is enough interest from the community.
