### ISSUE TITLE
Option to prevent "Profiling started" output

### ISSUE THREAD

**Issue by parttimenerd** [async-profiler/async-profiler#1031]
### Describe the feature

It would be better if the async-profiler could have a `--quiet` option, which would prevent any output in the command line.

### Use Case

This would make it easier to integrate into JTREG tests, allowing us to test async-profiler with the tests in our CI.

### Proposed Solution

Add a new flag, that configures the output stream. This should not prevent errors from being printed.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krk** [comment]
Profiler output respects log level now with https://github.com/async-profiler/async-profiler/pull/986, is this useful for your case?

**Comment by parttimenerd** [comment]
Oh, thank you, I didn’t know that.

**Comment by parttimenerd** [comment]
I reopened it, because it doesn't work :(

**Comment by krk** [comment]
Could you provide how you are starting the profiler and its parameters?

**Comment by apangin** [comment]
How do you start profiler exactly? Using `asprof` or `-agentpath`? What is a command line?
What output do you see?

**Comment by parttimenerd** [comment]
I’m starting it as an agent

**Comment by apangin** [comment]
@parttimenerd "It doesn't work" is not very helpful, sorry.
Can you please specify an exact command how you start profiler; what is an expected output and what do you see instead? Please also mention async-profiler and JDK versions.

Here is what I get running the latest profiler build from `master`:
```
$ java -agentlib:asyncProfiler=start -version
Profiling started
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment (build 23.0.1+11-39)
OpenJDK 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
Profiling stopped after 0 seconds. No dump options specified
```
Now with `loglevel=warn`:
```
$ java -agentlib:asyncProfiler=start,loglevel=warn -version
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment (build 23.0.1+11-39)
OpenJDK 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)
```

**Comment by parttimenerd** [comment]
I'm sorry, I made a mistake. You're right, it works now. Thank you for the clarification.
