### ISSUE TITLE
Nightly builds enhancements

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#1038]
### Describe the feature

Copied from the [comment](https://github.com/async-profiler/async-profiler/pull/1032#issuecomment-2423249168):

1. The name format should be `async-profiler-3.0-hash-arch.tar.gz` (hash should go before arch, that is, be a part of the full version number).
2. `PROFILER_VERSION` should be set accordingly to 3.0-hash, so that `asprof -v` returns the version number with a commit id.
3. Include artifacts from `build/jar` (async-profiler.jar and jfr-converter.jar) when publishing a release.

### Use Case

1. Improve developer experience.
2. Provide up-to-date binaries for JFR converter and async-profiler Java API.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krk** [comment]
We could run same tests (in MacOS, arm etc.) in all PRs, without updating the releases.
