### ISSUE TITLE
Update Wiki to Reference New Binary Launcher Instead of profiler.sh

### ISSUE THREAD

**Issue by karami4yasser** [async-profiler/async-profiler#1040]
### Describe the issue

Hi,

I've noticed that the wiki is still referencing the `profiler.sh` script in multiple places, although the new `asprof` binary launcher has been introduced. 
To address this, I created a local copy of the wiki and made the necessary changes in my repo:  
[https://github.com/karami4yasser/async-profiler/wiki](https://github.com/karami4yasser/async-profiler/wiki)

For example, on the homepage of the wiki, one section currently states:

---

**Current:**

> "The following is a complete list of the command-line options accepted by `profiler.sh` script."

**Suggested Update:**

> "The following is a complete list of the command-line options accepted by `asprof` binary launcher."

---

This is just one example; similar updates are needed throughout the wiki to ensure all references to `profiler.sh` are replaced with `asprof`. Feel free to review my modified version, and let me know if you'd like me to make any further adjustments.

Thanks for your attention!

**Comment by apangin** [comment]
Thank you for pointing this out.
We are currently in the progress of a major documentation rewrite: #1029
There will be a dedicated `docs` folder in the repository with all the documentation split into chapters. As a part of this work, we are adding more chapters on previously undocumented topics, such as JFR converter, Flame Graph interpretation, CPU profiling modes, etc. There is no intention to duplicate this information in the wiki. Therefore, let me just remove outdated wiki section.
