### ISSUE TITLE
Truncated thread names

### ISSUE THREAD

**Issue by lige955** [async-profiler/async-profiler#1042]
### Describe the bug

There is a phenomenon of thread names being truncated in the collected flame map. For example, Engine-11 was truncated as Engine-1, and Engine-12 was truncated as Engine-1.

### Async-profiler version

Async-profiler-3.0

**Comment by apangin** [comment]
What JVM version are you using?

**Comment by lige955** [comment]
> What JVM version are you using?

JDK17

**Comment by apangin** [comment]
> JDK17

I mean, a full **JVM** version.
What does `java -version` say?

Please also clarify how you start profiler and what profiler arguments are used.
Thanks.

**Comment by apangin** [comment]
I am closing the issue due to no response from the question author. There has been no similar issues reported so far.
My hypothesis is that it was Zing JVM. Async-profiler has limited support for Java thread names with Zing JVM.
