### ISSUE TITLE
Profiling report is missing

### ISSUE THREAD

**Issue by Sammers21** [async-profiler/async-profiler#1055]
### Describe the bug

Profiling report is missing

### Expected vs. actual behavior

I want profiling report being not missing, while its missing

### Reproduction Steps

```
➜  async-profiler-3.0-macos ls
CHANGELOG.md LICENSE      README.md    bin          lib
➜  async-profiler-3.0-macos ./bin/asprof -d 30 -f ./profile.html 42435
Profiling for 30 seconds
Done
➜  async-profiler-3.0-macos ls
CHANGELOG.md LICENSE      README.md    bin          lib
➜  async-profiler-3.0-macos
```

### Async-profiler version

3.0

### Environment details

MacOS 15.1, JDK 23, M2 max chip, just as a normal process

**Comment by Sammers21** [comment]
Also would be nice if after the profiling stops there would be a line that would point to the full path of the report.

**Comment by apangin** [comment]
Perhaps the same as #1045.
Please try a [newer version](https://github.com/async-profiler/async-profiler/releases/tag/nightly).

**Comment by Sammers21** [comment]
@apangin still does not work:
```
➜  async-profiler-3.0-603db84-macos ./bin/asprof -d 30 -f ./profile.html 42435
/Users/sammers/Downloads/async-profiler-3.0-603db84-macos/bin/../lib/libasyncProfiler.dylib was not loaded.
dlopen(/Users/sammers/Downloads/async-profiler-3.0-603db84-macos/bin/../lib/libasyncProfiler.dylib, 0x0001): tried: '/Users/sammers/Downloads/async-profiler-3.0-603db84-macos/bin/../lib/libasyncProfiler.dylib' (file system sandbox blocked open()), '/System/Volumes/Preboot/Cryptexes/OS/Users/sammers/Downloads/async-profiler-3.0-603db84-macos/bin/../lib/libasyncProfiler.dylib' (no such file), '/Users/sammers/Downloads/async-profiler-3.0-603db84-macos/bin/../lib/libasyncProfiler.dylib' (file system sandbox blocked open())
```

**Comment by apangin** [comment]
It's a different error now: `file system sandbox blocked open()`
Seems like macOS restricts loading binaries from the Downloads folder.

**Comment by Sammers21** [comment]
so how do i solve that issue?

**Comment by Sammers21** [comment]
@apangin okay so i did the thing with moving from the download folder. Its working now
