### ISSUE TITLE
System call "clock_gettime" use many CPU time slot

### ISSUE THREAD

**Issue by dliu-aspira** [async-profiler/async-profiler#1080]
### Describe the bug

System call "clock_gettime" use many CPU time slot.
libc.so.6.clock_gettime@GLIBC_2.2.5
![image](https://github.com/user-attachments/assets/e90dcd3b-ec2e-4e38-8e75-854ab43decda)

It may be caused by below code flow:
![image](https://github.com/user-attachments/assets/d90d5460-74ab-4255-aaeb-1e3ed31551e6)

### Async-profiler version

master

**Comment by apangin** [comment]
What you see on a flamegraph is not async-profiler's code. This comes from the application code.

Java `System.currentTimeMillis` and `System.nanotime` methods call `clock_gettime` under the hood, but being JVM intrinsics, they are not visible in a stack trace.

Try adding the following JVM options: `-XX:+UnlockDiagnosticVMOptions -XX:DisableIntrinsic=_currentTimeMillis,_nanoTime`. this will make `System.currentTimeMillis` and `System.nanotime` frames explicit in a profile (for a slightly bigger price of calling these methods).

**Comment by dliu-aspira** [comment]
Thanks, after turn on the JVM options, the System.currentTimeMillis use most of the time. But still don't know why "clock_gettime" use most of time.
![image](https://github.com/user-attachments/assets/8afd73ed-1b4a-44d9-8b0e-c9c1d4aed01a)

If it is related to clocksource?
bash-5.2$ cat /sys/devices/system/clocksource/clocksource0/available_clocksource 
tsc kvm-clock hpet acpi_pm 
bash-5.2$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource 
kvm-clock
bash-5.2$

**Comment by apangin** [comment]
> don't know why "clock_gettime" use most of time

How much does it take in % of the entire profile?
`clock_gettime` is typically fast when it does not fallback to a system call. If it makes a large portion of total CPU time, it probably means `System.currentTimeMillis` is just called too often.

> If it is related to clocksource?

`kvm-clock` should be OK. You may try setting it to `tsc`, but as mentioned above, this is unlikely to be an issue as long as it `clock_gettime` does not degrate to a syscall.
