### ISSUE TITLE
TTSP issue with liberica jdk 17

### ISSUE THREAD

**Issue by poisonriver** [async-profiler/async-profiler#1081]
### Describe the bug

Hi @apangin ,
I was trying to profile an application running under liberica jdk 17.0.1 and hit a wall. 
Using argument for `ttsp` I got an error:
**[ERROR] End address not found**
Changing it to explicit `begin/end` resulted in the same error.
Then I looked into the symbols of `libjvm` and didn't find `RuntimeService::record_safepoint_synchronized` there. More - there're no functions visible for `RuntimeService` at all.
liberica 11 and 12 are good, but 17 is missing a lot of symbols.
I tried to find any other possible function in the source code to trigger the end of TTSP profiling but nothing in the call chain is exported by liberica 17 libjvm. Or I just missed it.
Not sure if it's a bug, but other issues type looks wrong too.
May be you have any idea how to deal with it when I need to profile ttsp ?
Thanks

### Reproduction Steps

asprof -e wall -i 1ms --ttsp  -f ./profile.jfr

### Async-profiler version

3.0

### Environment details

CentOS 7
liberica jdk 17.0.x
x86_64

**Comment by apangin** [comment]
I remember early releases of Liberica JDK 17 were built with compiler options that resulted in "overoptimized" binaries that have very little symbols exposed. AFAIK this is no longer a case.
Can you check if the problem is still relevant to JDK 17.0.13? 17.0.1 is too old anyway.

**Comment by poisonriver** [comment]
> I remember early releases of Liberica JDK 17 were built with compiler options that resulted in "overoptimized" binaries that have very little symbols exposed. AFAIK this is no longer a case. Can you check if the problem is still relevant to JDK 17.0.13? 17.0.1 is too old anyway.

Yeah...you're right. 17.0.13 exports `RuntimeService::record_safepoint_synchronized` indeed.
The last one I had on the server was 17.0.7 with missing symbols as well, so I decided it was a dead end :-)
BTW, I also tried profiling with `--begin ShenandoahHeap::safepoint_synchronize_begin --end ShenandoahHeap::safepoint_synchronize_end` and got an empty JFR, although those calls look promising in the source code.
Thank you!

**Comment by apangin** [comment]
`-begin ShenandoahHeap::safepoint_synchronize_begin --end ShenandoahHeap::safepoint_synchronize_end` also work, but only with `-XX:+UseShenandoahGC`. An empty recording may mean there were no long enough time-to-safepoint pauses for the selected sampling interval. You can double check with [this example](https://github.com/async-profiler/async-profiler/blob/5ebc82dd040114569a090bfa719c60b27d2fa78f/test/test/jfr/Ttsp.java) that is known to cause long ttsp pauses.

**Comment by poisonriver** [comment]
Yes, I'm using Shenandoah GC.
May be you know how long should be time-to-safepoint pause to be captured by the profiler?

**Comment by apangin** [comment]
> how long should be time-to-safepoint pause to be captured by the profiler?

It matches sampling interval.
With the default CPU sampling interval of 10 ms, a thread that delays safepoint should actively run on CPU for at least 10 ms to be captured for sure. Sampling interval can be configured with `-i` option.

Sometimes a thread may delay safepoint even when not running on CPU, for example, by accessing a memory-mapped file and causing swap-in. In these cases, CPU profiling mode will not catch such a thread, but the Wall-clock mode will.

**Comment by poisonriver** [comment]
I set sampling interval to 1ms and having Reaching safepoint: 1150301758 ns in log still no threads information recorded.
Looks like the only option is to upgrade to 17.0.13

**Comment by apangin** [comment]
I hope the question is answered. Let me know if anything else is needed on the profiler end.

Note that in some cases async-profiler won't be able to detect TTSP pause, if it is caused by external factors: e.g., if the whole process does not receive CPU time from the OS for whatever reason, async-profiler will not work either, since it runs in the context of the process being profiled.
