### ISSUE TITLE
Unable to profile in container despite setting -e ctimer

### ISSUE THREAD

**Issue by murugaratham** [async-profiler/async-profiler#1088]
### Describe the bug

unable to profile in container despite setting -e ctimer

### Reproduction Steps

xx@container[java-test]:/home/xx# ./asprof 1
Target JVM failed to load asyncProfiler
xx@container[java-test]:/home/xx# java -agentpath:/home/xx/libasyncProfiler.so=start,flat -version -e ctimer
[WARN] Kernel symbols are unavailable due to restrictions. Try
  sysctl kernel.perf_event_paranoid=1
  sysctl kernel.kptr_restrict=0
[WARN] perf_event_open for TID 1466 failed: Operation not permitted
[WARN] perf_event_open for TID 1467 failed: Operation not permitted
[WARN] perf_event_open for TID 1468 failed: Operation not permitted
[WARN] perf_event_open for TID 1469 failed: Operation not permitted
[WARN] perf_event_open for TID 1470 failed: Operation not permitted
[WARN] perf_event_open for TID 1471 failed: Operation not permitted
[WARN] perf_event_open for TID 1472 failed: Operation not permitted
[WARN] perf_event_open for TID 1473 failed: Operation not permitted
[WARN] perf_event_open for TID 1474 failed: Operation not permitted
[WARN] perf_event_open for TID 1475 failed: Operation not permitted
[WARN] perf_event_open for TID 1476 failed: Operation not permitted
[WARN] perf_event_open for TID 1477 failed: Operation not permitted
[WARN] perf_event_open for TID 1478 failed: Operation not permitted
[WARN] perf_event_open for TID 1479 failed: Operation not permitted
[WARN] perf_event_open for TID 1480 failed: Operation not permitted
[WARN] perf_event_open for TID 1481 failed: Operation not permitted
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'
java version "17.0.13" 2024-10-15 LTS
Java(TM) SE Runtime Environment (build 17.0.13+10-LTS-268)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.13+10-LTS-268, mixed mode, sharing)
xx@container[java-test]:~#

### Async-profiler version

Async-profiler 3.0 built on Jan 20 2024

### Environment details

Running on eks

**Comment by apangin** [comment]
You've passed `-e ctimer` as a `java` argument, not async-profiler argument.
Use `-e ctimer` when running `asprof`. When loading async-profiler as an agent library, use an equivalent `event=ctimer` option:
```
java -agentpath:/home/xx/libasyncProfiler.so=start,event=ctimer,flat -version
```

Since last month, async-profiler automatically falls back to `ctimer` if perf_events are unavailable, see https://github.com/async-profiler/async-profiler/issues/1044#issuecomment-2453774949.
The change is already available in [Nightly builds](https://github.com/async-profiler/async-profiler/releases/tag/nightly).
