### ISSUE TITLE
Continuos profiling converter enhancements

### ISSUE THREAD

**Issue by franz1981** [async-profiler/async-profiler#556]
While running continuos profiling using multiple events, depending on the whole profiling session duration (and `--loop` granularity), it could be necessary convert multiple jfr files using a similar name pattern into respective flamegraphs ones with a single command. I would be nice to have it embedded in the converter command, wdyt @apangin ?

**Comment by franz1981** [comment]
Just for the records, with linux, it's still possible to do something like:
```
$ for file in ./*.jfr; do java -cp build/converter.jar jfr2flame "$file" "${file%.jfr}"_cpu.html; done;
```
using https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

But it still means creating many java machines instead of just one

**Comment by apangin** [comment]
Thank you for a proposal. While this feature can be useful in some cases, I would rate it as a low priority enhancement. As you mentioned, a bash one-liner can solve the problem. Or a simple Java application may call `jfr2flame` multiple times in the same JVM.

**Comment by schlosna** [comment]
Along the lines of continuous profiling, I am interested in using the converters such as `jfr2flame` from a longer running service that converts input JFRs. 

One issue I ran into when prototyping this was that many of the converter types such as [`jfr2flame`, `Arguments`, `FlameGraph` are in the default package](https://github.com/jvm-profiling-tools/async-profiler/tree/master/src/converter) so are not easy to consume as a library (e.g. it is possible via reflection, though noisy). Would you be open to PRs to expose these types in a proper package (e.g. `one.jfr.converter`)?

**Comment by apangin** [comment]
@schlosna Can you please elaborate what is exactly the problem with top-level classes? I can easily use them from another app/library.

**Comment by apangin** [comment]
Support for multiple input files in one command has been added in #905.
The same commit moves top-level classes to `one.converter` package.

**Comment by franz1981** [comment]
Thanks @apangin !
