### ISSUE TITLE
Utilize fdtransfer to share memory between different cgroups

### ISSUE THREAD

**Issue by Jongy** [async-profiler/async-profiler#646]
One common issue with async-profiler is the fact it runs in the same context as the profiled app, and consumes resources from the profiled app (be it memory / CPU / ...).

I'm thinking of ways to improve that - i.e to have async-profiler's resource usage by "invisible" to the app and not accounted on the app. This way we cannot cause OOMs, etc.
An idea I had recently and wanted to hear your thoughts on it, @apangin, is - avoid using `mmap`/`malloc` in the agent, and instead utilize the connection of fdtransfer to request a memory chunk from the server. The server could allocate shared memory with `shm_open`, then `mmap`s it and touches the pages. By touching the pages, they will be accounted on the cgroup of ftransfer itself. The agent can then `mmap` the fds as well, and get "free memory" that will not be accounted on its cgroup.

Do you think this will reduce most of async-profiler's memory usage in the target process? (i.e is `LinearAllocator` most of the used memory, or something else?)

**Comment by apangin** [comment]
This is an interesting idea, but I wouldn't be so definitive saying that profiler's memory accounted to a Java process is a common issue. I know several companies running async-profiler continuously on hundreds Java applications in a cloud, and there were no complaints about excessive memory usage (well, there were, but those problems were a result of either misconfiguration or bugs that have been found and fixed).

If you are aware of certain memory issues, please report and we'll figure out how to deal with them. I recently added `meminfo` command to estimate profiler's memory usage. Most often, the biggest consumer is the call trace storage (which includes stack traces + hashtables for them). But that's not the only thing; profiler also allocates memory for various dictionaries, buffers, symbol tables, dwarf unwinding info, etc. I don't think offloading all these allocations to other process is practical. Even if we consider only the call trace storage, it sometimes requests new pages directly from a signal handler; RPC inside a signal handler doesn't seem a right thing to do.

**Comment by Jongy** [comment]
I don't have any evidence for memory issues, it's just something I had in my mind while trying to reduce the effects on the profiled process.

I saw your recent `meminfo` addition - I will give it a try and collect some metrics, and get back here once I have real data :)

**Comment by apangin** [comment]
Let me close the issue as there was hardly any demand for it.
However, I'm open to get back to discussion if there is new input.
