### ISSUE TITLE
Broken symbols when ELF `p_offset != p_vaddr` in the executable segment

### ISSUE THREAD

**Issue by markj-db** [async-profiler/async-profiler#689]
`async-profiler` finds the start of the ELF file by [jumping back `p_offset` bytes](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/symbols_linux.cpp#L608) from the address where it finds the executable segment in `/proc/self/maps`.

Since https://reviews.llvm.org/D64903, `lld` produces libraries (by default) where the start of the executable segment is not necessarily aligned to a page boundary.  As a consequence, it produces a layout where `p_offset <= p_vaddr`.  (IIUC, ELF files with this property can also be generated under other circumstances, it just happens to be this specific trigger is the root cause of my own issues.)

When `p_offset != p_vaddr`, `async-profiler` looks for program headers in the wrong location and fails to load the DWARF data.  It also supplies the wrong base address when loading symbols, causing symbol resolution to be wrong (e.g. nonsense call stacks in native code -- that is, call stacks that include caller-callee relationship that don't exist in practice). Specifically, the `image_base` passed to `ElfParser::parseProgramHeaders` and `ElfParser::parseFile` is off by `p_vaddr - p_offset` bytes.

As an example, if I have a library with the following layout:

```
$ readelf -Wl libfoo.so
...
Entry point 0x64dd180
...
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
...
  LOAD           0x64dc180 0x00000000064dd180 0x00000000064dd180 0x6813120 0x6813120 R E 0x1000
...
```

This library will map into memory (for example) as:

```
# snippet from /proc/self/maps
...
7f7562d7d000-7f756925a000 r--p 00000000 103:01 4162946                   /libfoo.so
7f756925a000-7f756fa6e000 r-xp 064dc000 103:01 4162946                   /libfoo.so
...
```

`async-profiler` looks for an ELF header at `0x7f756925a000 - 0x64dc000 = 0x7f7562d7e000`, which is `0x1000` ahead of where the actual ELF header is located.

I confirmed that I can hack around this by modifying `Symbols::parseLibraries` to do the following:

 1. look for an ELF header at `image_base -= map.offs();`
 2. if the ELF header is not found, try looking a second time at `image_base -= 0x1000;`

For my sample library `libfoo.so` above, condition 1 fails and condition 2 finds the ELF header.

I also confirmed that symbol lookup is correct in `async-profiler` if I link my library with `-z separate-code`.

I think a more robust fix for `async-profiler` might be to remember the base address of the library when it's seen during the read of `/proc/self/maps` (i.e. when a library is seen with offset `0x0`, remember that base address and use it as the `image_base` for `ElfParser::parseProgramHeaders` and `ElfParser::parseFile` instead of trying to jump back from the virtual address of the executable segment).

Alternatively, I believe there are libraries that might be able to help with this (e.g. [`dl_iterate_phdr`](https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-dl-iterate-phdr-1.html), which is used by [`libbacktrace`](https://github.com/ianlancetaylor/libbacktrace)).  Using this would be a more intrusive change to `async-profiler` and may be undesirable for other reasons that I'm not aware of.

**Comment by apangin** [comment]
Thank you for the analysis. I tried to use `dl_iterate_phdr` (see `dl-iter` branch), but it is also not reliable on some systems.
More details in #669.
I'll investigte this deeper.

**Comment by modiking** [comment]
>I confirmed that I can hack around this by modifying Symbols::parseLibraries to do the following:
> 1. look for an ELF header at image_base -= map.offs();
> 2. if the ELF header is not found, try looking a second time at image_base -= 0x1000;

Since the offset is specifically off by `p_vaddr - p_offset` we can directly calculate this value as a modifier. This is made easier as the ELF spec says (https://refspecs.linuxfoundation.org/elf/elf.pdf):
```
Though the system chooses virtual addresses
for individual processes, it maintains the segments’ relative positions. Because
position-independent code uses relative addressing between segments, the difference between
virtual addresses in memory must match the difference between virtual addresses in the file.
The difference between the virtual address of any segment in memory and the corresponding
virtual address in the file is thus a single constant value for any one executable or shared object
in a given process. This difference is the base address. One use of the base address is to relocate
the memory image of the program during dynamic linking.
```

Essentially `p_vaddr - p_offset` will be constant for all memory mappings to maintain relative addressing. We only need to calculate this value once and trust that it'll be correct for all values. Our approach inside Meta is to find the lowest mapping and apply this. For example:

```
7ffff56ab000-7ffff5e0b000 r--p 00000000 00:23 297638982 libjvm.so
7ffff5e0b000-7ffff71f0000 r-xp 0075f000 00:23 297638982 libjvm.so
...
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x000230 0x000230 R   0x8
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x75f464 0x75f464 R   0x1000
  LOAD           0x75f470 0x0000000000760470 0x0000000000760470 0x13e4160 0x13e4160 R E 0x1000
If we operate on the first loadable segment:
1. (mmStartAddr - mmFileOffset) - (lowest p_vaddr - lowest p_offset) becomes (0x7ffff56ab000 - 0x0) - (0x0 - 0x0) = 0x7ffff56ab000 which is the correct base address.
1. Assuming for whatever reason the first segment is not loadable, (mmStartAddr - mmFileOffset) - (lowest p_vaddr - lowest p_offset) becomes (0x7ffff5e0b000 - 0x75f000) - (0x760470 - 0x75f470) = 0x7ffff56ac000 - 0x1000 = 0x7ffff56ab000 which is still correct. The correction factor comes from how the virtual address and offset may no longer line up.
```

**Comment by apangin** [comment]
@modiking The whole idea of parsing Program Headers in async-profiler is to deal with cases when .so file is not accessible / deleted. If I could get `p_vaddr`/`p_offset` from the original ELF file, I would be as well able to get all the rest info from the file directly.

Since I can't rely either on .so file or `dl_iterate_phdr`, the best bet is to find the image base from the very first mapping like @markj-db suggested.

**Comment by modiking** [comment]
@apangin Sounds like a plan.

**Comment by apangin** [comment]
The fix has been committed. Please try and report back any issues.
