### ISSUE TITLE
SIGSEGV during dump on OpenJ9 with activated ClassGC

### ISSUE THREAD

**Issue by lixfel** [async-profiler/async-profiler#691]
With activated ClassGC async-profiler segfaults OpenJ9 repeatably during profile dump.

gdb stacktrace of core dump:
![image](https://user-images.githubusercontent.com/26159085/204786494-fafcb1d1-965f-4863-a1fd-8aefb5d19bc3.png)
(Segfaulting in https://github.com/eclipse-openj9/openj9/blob/master/runtime/jvmti/jvmtiClass.c#L315)

Reproduced with Java-API and embedded profiling with Java agent (others untested). Reproduced with cpu and wall profiling (others untested). Other JVMs untested. The issue could not be reproduced with `-Xnoclassgc`.

I don't have solid evidence for the class gc as issue source (don't have done gc logs yet), but the strong correlation with `-X(no)classgc` is enough for my assumption.

**Comment by apangin** [comment]
Seems a JVM bug to me.
Async-profiler does nothing fancy in the wall-clock mode - just calls regular JNI/JVMTI functions and J9-specific extensions. The crash happens in the JVM when trying to resolve `jmethodID` that was previously returned by the same JVM.

**Comment by apangin** [comment]
I'm going to close this issue, since there is nothing to do on async-profiler end.
