### ISSUE TITLE
mprotect graph has huge "_mprotect" section

### ISSUE THREAD

**Issue by pmaru10** [async-profiler/async-profiler#700]
We noticed a bump in RSS usage around the time we profiled the process for 'mprotect' event. The majority of the graph was filled with just a "mprotect" function call. What do we make out of it?
<img width="1707" alt="Screen Shot 2022-12-15 at 2 01 30 PM" src="https://user-images.githubusercontent.com/107007201/207976782-3fdc8747-8e31-4fbd-8f92-13e23fb24010.png">

**Comment by apangin** [comment]
Use `--cstack dwarf` to get stack traces below `mprotect`

**Comment by apangin** [comment]
For new profiles

**Comment by pmaru10** [comment]
Hi Andrei, 

Thanks. One more quick question - I have an application whose RSS jumps very quickly (in less than a min or two) by 20+G and eventually crashes the system. Do you think profiling 'mprotect' might be better, or should I use the 'nativemem' profiler?  or let me know, if you think profiling for any other events might be more suitable here.

Thanks.

**Comment by krzysztofslusarski** [comment]
With such a rapid growth ```mprotect``` or ```page-faults``` should do the trick.

**Comment by pmaru10** [comment]
Thanks @krzysztofslusarski for the reply.

As per @apangin suggestions, I have enabled "--cstack dwarf", after which I see the following.  Any pointers on how to read this? 

<img width="1709" alt="Screen Shot 2022-12-16 at 8 10 27 PM" src="https://user-images.githubusercontent.com/107007201/208224290-1b512ba7-2aae-44f2-8cde-1a31e9e17ed0.png">

**Comment by apangin** [comment]
The graph shows that the most native allocations happen during JIT compilation and when cleaning up previously JITted code. This is not yet a sign of a memory leak. If this code leaks, this will mean a JVM bug (there were such bugs in the past).

Did you try `nativemem` profiling?
https://github.com/jvm-profiling-tools/async-profiler/blob/malloc/README.md#finding-native-memory-leaks

**Comment by krzysztofslusarski** [comment]
@pmaru10 
Can you paste the output from native memory tracking (summary) when you have high RSS? 
Can you paste your JVM arguments and java version?

**Comment by apangin** [comment]
The original question seems to be answered.
Closing the issue in the absense of further feedback.
