### ISSUE TITLE
AllocTracer is used with `--alloc` even with a JVM without debug symbols

### ISSUE THREAD

**Issue by parttimenerd** [async-profiler/async-profiler#714]
This leads async-profiler to not profile anything.

The async-profiler errors is
```
[WARN] Install JVM debug symbols to improve profile accuracy
[ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?
```

First reported by @I-Al-Istannen in https://github.com/parttimenerd/intellij-profiler-plugin/issues/8

**Comment by apangin** [comment]
The fix is to choose `ObjectSampler` for allocation profiling when available. It does not depend on debug symbols.

**Comment by linany** [comment]
V2.10 still hava this problem， how can i deal it？

**Comment by apangin** [comment]
@linany What problem exactly are you seeing? What JDK version do you use? On which platform?

**Comment by linany** [comment]
> @linany What problem exactly are you seeing? What JDK version do you use? On which platform?

@apangin I encountered the same issue when I use V2.10, **problem** ：
`[WARN] Install JVM debug symbols to improve profile accuracy
[ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?
` 
**JDK version** ：
`openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)`  
**platform** ：
`Linux version 5.4.0-109-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022`

**Comment by apangin** [comment]
@linany It's not the same issue. You run JDK 8, and to use allocation profiling on JDK 8, you *need* JVM debug symbols installed. See [Installing Debug Symbols](https://github.com/async-profiler/async-profiler/?tab=readme-ov-file#installing-debug-symbols)
