### ISSUE TITLE
ContendedLock doesn't work for jdk.JavaMonitorEnter

### ISSUE THREAD

**Issue by RaymondLam1** [async-profiler/async-profiler#715]
* Thank you for your work firstly. When I use `jfr2flame.java`, I found it dosen't work for `jdk.JavaMonitorEnter` and it works for `jdk.ThreadPark`. It is a bug ?
* I use Oracle jmc, it shows I hava many JavaMonitorEnter events, but I get nothing stack flame view by use `jfr2flame.java`.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/96219320/219359123-c24be045-e1cd-49d3-9440-5fa4cc95a4c3.png">

**Comment by apangin** [comment]
Your screenshot highlights many events named `Java Monitor Wait`, which is a label for `jdk.JavaMonitorWait`. This is not a contended lock.

The contended locks are marked by `jdk.JavaMonitorEnter` events titled `Java Monitor Blocked`. There are 0 such events on the screenshot.

**Comment by RaymondLam1** [comment]
* I'm very happy to have received your response. I'm ashamed of making a simple mistake.
