### ISSUE TITLE
Profiling crashes JVM if GC thread running

### ISSUE THREAD

**Issue by infa-jmashalk** [async-profiler/async-profiler#720]
We have recently started running async profiler on our production systems, which are typically at over 90% of memory. 
Following are the GC settings:
-XX:+UseG1G
-XX:ConcGCThreads=9 
-XX:G1HeapRegionSize=16777216
-XX:+ParallelRefProcEnabled
-XX:+PrintSafepointStatistics -XX:PrintSafepointStatisticsCount=1
-XX:InitiatingHeapOccupancyPercent=40

Over a span of three days, we have seen the profiler to cause the application jvm process to crash. 
Profiler is being run seperately using the command below:
./profiler.sh -d 120 -e alloc -t -f test.jfr <pid>

Upon analysis of the hs_err file, its seen to crash in a thread running the con mark activity for GC. Following is the first part of information from of the two files analysed. Rest has been witheld due to company security policies:
File 1:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f0f0a6ba594, pid=24090, tid=0x00007f0ef4659700

 JRE version: OpenJDK Runtime Environment (Zulu 8.64.0.20-SA-linux64) (8.0_345-b01) (build 1.8.0_345-b01)
 Java VM: OpenJDK 64-Bit Server VM (25.345-b01 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x444594]  ClassLoaderData::oops_do(OopClosure*, KlassClosure*, bool)+0x4

 Core dump written. Default location: //core or core.24090

 If you would like to submit a bug report, please visit:
   http://www.azul.com/support/

---------------  T H R E A D  ---------------

Current thread (0x00007f0f04056000):  ConcurrentGCThread [stack: 0x00007f0ef455a000,0x00007f0ef465a000] [id=24121]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000024

Stack: [0x00007f0ef455a000,0x00007f0ef465a000],  sp=0x00007f0ef4658cf8,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x444594]  ClassLoaderData::oops_do(OopClosure*, KlassClosure*, bool)+0x4
V  [libjvm.so+0x4a7307]  CMTask::do_marking_step(double, bool, bool)+0xc77
V  [libjvm.so+0x4ad824]  CMConcurrentMarkingTask::work(unsigned int)+0x1e4
V  [libjvm.so+0xb6b208]  GangWorker::loop()+0xd8
V  [libjvm.so+0x970c82]  java_start(Thread*)+0x102

=>0x00007f8718056000 (exited) ConcurrentGCThread [stack: 0x00007f8708cfe000,0x00007f8708dfe000] [id=24694]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x00000002c0000000, size: 20480 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x00000007c0000000

Heap:
 garbage-first heap   total 20971520K, used 11322019K [0x00000002c0000000, 0x00000002c1002800, 0x00000007c0000000)
  region size 16384K, 151 young (2473984K), 19 survivors (311296K)
 Metaspace       used 298758K, capacity 348082K, committed 439424K, reserved 1425408K
  class space    used 37378K, capacity 47941K, committed 63360K, reserved 1048576K

---------------  S Y S T E M  ---------------

OS:CentOS Linux release 7.9.2009 (Core)

uname:Linux 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
libc:glibc 2.17 NPTL 2.17 
rlimit: STACK 8192k, CORE infinity, NPROC infinity, NOFILE 130001, AS infinity
load average:3.57 2.48 2.84

Memory: 4k page, physical 32470380k(675844k free), swap 49283064k(48730360k free)

vm_info: OpenJDK 64-Bit Server VM (25.345-b01) for linux-amd64 JRE (Zulu 8.64.0.20-SA-linux64) (1.8.0_345-b01), built on Aug  2 2022 06:38:58 by "zulu_re" with gcc 7.3.0

---------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
File 2:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f871ee5491a, pid=24665, tid=0x00007f8708dfd700

 JRE version: OpenJDK Runtime Environment (Zulu 8.64.0.20-SA-linux64) (8.0_345-b01) (build 1.8.0_345-b01)
 Java VM: OpenJDK 64-Bit Server VM (25.345-b01 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 V  [libjvm.so+0x4ac91a]  CMTask::make_reference_grey(oopDesc*, HeapRegion*)+0x32a

 Core dump written. Default location: //core or core.24665

 If you would like to submit a bug report, please visit:
   http://www.azul.com/support/

---------------  T H R E A D  ---------------

Current thread (0x00007f8718056000):  ConcurrentGCThread [stack: 0x00007f8708cfe000,0x00007f8708dfe000] [id=24694]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000008

Stack: [0x00007f8708cfe000,0x00007f8708dfe000],  sp=0x00007f8708dfcc60,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x4ac91a]  CMTask::make_reference_grey(oopDesc*, HeapRegion*)+0x32a
V  [libjvm.so+0x444610]  ClassLoaderData::oops_do(OopClosure*, KlassClosure*, bool)+0x80
V  [libjvm.so+0x66c39f]  InstanceMirrorKlass::oop_oop_iterate_nv(oopDesc*, G1CMOopClosure*)+0x5f
V  [libjvm.so+0x4a7307]  CMTask::do_marking_step(double, bool, bool)+0xc77
V  [libjvm.so+0x4ad824]  CMConcurrentMarkingTask::work(unsigned int)+0x1e4
V  [libjvm.so+0xb6b208]  GangWorker::loop()+0xd8
V  [libjvm.so+0x970c82]  java_start(Thread*)+0x102

=>0x00007f0f04056000 (exited) ConcurrentGCThread [stack: 0x00007f0ef455a000,0x00007f0ef465a000] [id=24121]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

---------------  S Y S T E M  ---------------

OS:CentOS Linux release 7.9.2009 (Core)

uname:Linux 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
libc:glibc 2.17 NPTL 2.17 
rlimit: STACK 8192k, CORE infinity, NPROC infinity, NOFILE 130001, AS infinity
load average:5.54 5.38 3.81

vm_info: OpenJDK 64-Bit Server VM (25.345-b01) for linux-amd64 JRE (Zulu 8.64.0.20-SA-linux64) (1.8.0_345-b01), built on Aug  2 2022 06:38:58 by "zulu_re" with gcc 7.3.0

Is there any limitation of async profiler with respect to G1GC? 
PS: perf events has not been enabled on this system due to security issues

**Comment by apangin** [comment]
Do I understand correctly that the crash happens only with JDK 8 and only when allocation profiling is enabled?
If so, this is likely a duplicate of #694

**Comment by infa-jmashalk** [comment]
Yes thats correct, its possibily similar to the issue mentioned here. Thank you Andrei for digging it up so quickly. Few follow up questions
- Just to confirm, this happens in the original issue when async profiler is run as a background process, not attached as an agent? 
- Is this particular to any particular JDK version or GC algorithm? 
- Any rough ETA on the fix? 
- Any workarounds, or any suggestions to mitigate the issue, so that we can use async profiler to profile memory allocations?

**Comment by apangin** [comment]
Unfortunately, I can't tell more details at this point, unless I have a reliable way to reproduce the issue.

**Comment by zdyj3170101136** [comment]
> 不幸的是，我目前无法透露更多细节，除非我有可靠的方法来重现该问题。

is this already fixed or there is other way to fix it?

**Comment by apangin** [comment]
This issue has been closed as a duplicate of #694. Please post further comments on the origin issue.
