### ISSUE TITLE
Statically link libstdc++ at least for musl builds

### ISSUE THREAD

**Issue by rrva** [async-profiler/async-profiler#729]
A lot of jdk docker images are
based on alpine without libstdc++ preinstalled. It is great to be able to use libasyncprofiler without having to modify the docker image that java is running on.

Please link libstdc++ statically but keep other dependencies like musl libc dynamically linked.

I can make a pull request if this is something that would be ok to have in all musl release builds, I am guessing something like this

`g++ -shared -o your_library.so your_object_files.o -static-libstdc++ -Wl,-Bdynamic -lc
`

**Comment by Jongy** [comment]
We're building AP with `-static-libstdc++` on musl in our async-profiler fork used in gProfiler. For reference [this is the change](https://github.com/Granulate/async-profiler/commit/49080a221b46e312041947ebbf7845dc054b4438). Note that it greatly increases the size (300-400k -> 8mb).

As a generic solution we might want to have 2 separate AP builds, one static and one not static, because not all musl-based JVMs lack libstdc++, so we can use the appropriate one. (to reduce memory overhead & loaded code, etc).

**Comment by apangin** [comment]
As @Jongy noticed, static linking may significantly impact the library size - this is not something that can be done unconditionally. At the same time, I don't want to multiply the number of builds.
Ideal solution would be to get rid of `libstdc++` dependency at all. This is doable but requires a fair amount of routine.

**Comment by rrva** [comment]
Would it not be possible to add the libstdc++.so to the jar file which already contains libasyncprofiler.so ? I bet there is a way to set LD_LIBRARY_PATH so it would only load this copy if libstdc++ is non-existent on the system, and libstdc++ should be known at build time which version of it is the compatible one, so it could be included in the jar. This way, there is no increase in memory usage that can be seen with static linking, but asyncprofiler is usable on stock docker images where libstdc++ is not preinstalled (most notably a lot of alpine based openjdk distributions). This or the rewrite where libstdc++ is removed completely (but I can understand if that is a larger task)

**Comment by apangin** [comment]
You can build `libasyncProfiler.so` statically linked with `libstdc++` with no modifications to async-profiler source code by passing custom `CXXFLAGS` value to `make` command.

We have no plans to provide multiple builds of `libasyncProfiler.so` that differ only by used compiler/linker flags. At the same time we welcome changes that will _decrease_ the number of produced binaries and thus improve user experience and reduce maintenance overhead. As mentioned above, one of the possible approaches to that is getting rid of `libstdc++` dependency altogether.

**Comment by apangin** [comment]
Closing this issue in favor of #872.
