### ISSUE TITLE
for docker, I use --fdtransfer, but it not work 

### ISSUE THREAD

**Issue by zhuyixiang** [async-profiler/async-profiler#730]
I use it like this :
./profiler.sh --fdtransfer -f start 1    
than i got this response:
[WARN] perf_event_open for TID 5089 failed: Operation not permitted
[WARN] perf_event_open for TID 5091 failed: Operation not permitted
[WARN] perf_event_open for TID 5092 failed: Operation not permitted
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'

I want to know how to use --fdtransfer in docker

**Comment by apangin** [comment]
The whole point of `--fdtransfer` option is to profile unprivileged containers (that do not have access to perf_events) from a privileged environment: from the host OS under `root` account or from a separate container with ADMIN capabilities.

If you have root access on the host, use can use `--fdtransfer` option when running `profiler.sh` from there.

For profiling inside a restricted container you can only use `-e itimer` option (which is fine, but will not show you kernel stack traces).

**Comment by zhuyixiang** [comment]
I got it, thanks

**Comment by zhuyixiang** [comment]
could I use  --security-opt seccomp=/path/to/seccomp/profile.json , just config perf event open and some system call for it.
https://docs.docker.com/engine/security/seccomp/

**Comment by zhuyixiang** [comment]
I add cap add: - SYS_ADMIN for docker, it work ok. 
But we don't want use SYS_ADMIN, it is too high, we want to minimize privileges.
So, we want to use docker seccomp, 
https://docs.docker.com/engine/security/seccomp/
could you please give me some  suggestion？？

**Comment by apangin** [comment]
You can modify an existing seccomp policy file (`/usr/share/containers/seccomp.json` or `/etc/docker/seccomp.json`) to exclude `perf_event_open` from the restriction list. Alternatively, create a new similar policy file and pass it with `--security-opt` option when starting docker.

**Comment by apangin** [comment]
I assume the question is answered. Feel free to open a new issue if you have further questions.
