### ISSUE TITLE
impossible stack trace when inline happens

### ISSUE THREAD

**Issue by heifrank** [async-profiler/async-profiler#732]
We use async profiler to do performance analysis. Recently we found a strange flame graph in which some stack trace should not appear.

![image](https://user-images.githubusercontent.com/5356131/227147206-5048b3d1-c5de-4e81-9d97-a5c74aee1593.png)

the flame graph is started after the program executes some period(in a steady state)，the newCapacity method should not appear(sometimes we can even see Arrays.copyOf stack which should not appear either) since Base64 will precompute the total size and I checked the logic is right.

the tested code is below and it's always reproduceble

```
import com.google.common.io.BaseEncoding;

public class BB {

  public static void main(String[] args) {
    byte[] bytes = {1, 2, 3};
    int tot = 0;
    while (true) {
      String encode = doEncode(bytes);
      tot += encode.length();
    }
  }

  private static String doEncode(byte[] bytes) {
    return BaseEncoding.base64().encode(bytes);
  }
}
```

Other infos:
jdk version: JDK 17 AND jdk8
platform: both macos and centos7

I tried
* starting the program in -Xint mode 
* disable jit compile the relate method: -XX:+UnlockDiagnosticVMOptions -XX:CompileCommand="dontinline java.util.Arrays::copyOf" -XX:CompileCommand="dontinline java.lang.AbstractStringBuilder::newCapacity" -XX:CompileCommand="dontinline java.lang.AbstractStringBuilder::ensureCapacityInternal" -XX:+PrintInlining

both will report correct stack trace(the top frame is always ensureCapacityInternal, no further Arrays.copyOf or newCapacity will appear)

I also tried adding DebugNonSafePoints when starting jvm, which won't help either. 

I want to know if it's jit inline bug or async profiler bugs.

**Comment by krzysztofslusarski** [comment]
Probably JDK-8281677, JDK-8201516.

**Comment by apangin** [comment]
You are right, it is https://bugs.openjdk.org/browse/JDK-8201516.
I verified the flame graph is correct with JDK 21.

**Comment by heifrank** [comment]
> You are right, it is https://bugs.openjdk.org/browse/JDK-8201516. I verified the flame graph is correct with JDK 21.

@apangin 
I double check the DebugNonSafePoints parameter，and found some info i gave before is a little misleading.

* flame graph is wrong when -XX:+DebugNonSafePoints on jdk8
* flame graph is right when  -XX:+DebugNonSafePoints on jdk17
* flame graph is wrong both on jdk8 and jdk17 when DebugNonSafePoints is not enabled.

JDK17 info:
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

so i'm not sure my problem is the same bug as you mentioned.
