### ISSUE TITLE
Show targets of vtable/itable calls

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#736]
In some applications, a signiticant amount of CPU time is spent on dispatching megamorphic virtual/interface calls. This appears in the profile as `vtable stub` or `itable stub`. However, this does not give any clue on why the particular call site is megamorphic and how to optimize it.

I propose adding a pseudo-frame on top of `v/itable stub` with the actual type of an object the virtual method is called on. This should make clear the propotion of different receivers for the particular call site:

<img width="762" alt="vtable" src="https://user-images.githubusercontent.com/1749416/228115589-e1b8186c-e7e1-4e3e-bc5d-69f4cb63daa3.png">

**Comment by apangin** [comment]
New feature is turned on by default, but can be disabled with `--safemode 0x40` option.

**Comment by krzysztofslusarski** [comment]
Great feature, thank you.

**Comment by yanglong1010** [comment]
Great feature

**Comment by toaler** [comment]
How do we use this with JMH?

-prof "async:libPath=/home/foo/Downloads/async-profiler-3.0-linux-x64/lib/libasyncProfiler.so;output=jfr;dir=direction;rawCommand=-F vtable"

Yields:

# Run progress: 50.00% complete, ETA 00:00:02
# Fork: 1 of 1
# Preparing profilers: AsyncProfiler 
# Warmup Iteration   1: [WARN] Unknown argument: -F vtable
100.598 us/op
Iteration   1: [WARN] Unknown argument: -F vtable

**Comment by apangin** [comment]
@toaler Async-profiler plugin for JMH is a part of [JMH project](https://openjdk.org/projects/code-tools/jmh/).
You may use `rawCommand` option to pass raw async-profiler command line to the plugin:
```
-prof async:rawCommand=features=vtable
```

**Comment by toaler** [comment]
Thanks @apangin , when I run:

-prof async 

I get vtable/itable frames

when I run:

-prof async:rawCommand=features=vtable

The vtable frames are not included. Infact any time I set a option via -prof async like

-prof async:output=jfr;rawCommand=features=vtable

vtable is ignored.

**Comment by apangin** [comment]
@toaler 
It worked for me. Make sure to enclose the argument in quotes: `-prof "async:output=jfr;rawCommand=features=vtable"`, otherwise bash will treat `;` as a command separator.
Also note that you need async-profiler version 3.0 to use this feature.

**Comment by toaler** [comment]
Thanks that solved it
