### ISSUE TITLE
Why is async-profiler not linking musl statically?

### ISSUE THREAD

**Issue by v-thakkar** [async-profiler/async-profiler#742]
This is not much of an issue but a question. I wasn't sure where to ask it so opening an issue here. I see that `async-profiler` links musl dynamically. This makes the binary less self-contained and dependent on the target container platform. Is there a specific reason why it isn't linked statically? I saw that there is an ongoing effort [here](https://github.com/async-profiler/async-profiler/issues/733) to make a single binary work for both glibc and musl but I'm not sure if musl will still be dynamically linked as part of it? I'm aware that statically linked musl binaries will be bigger in size but was just wondering if there are any other async-profiler specific reasons for the same.

Thanks!

**Comment by apangin** [comment]
The question has been discussed in #729.
I'll close this one as duplicate.
