### ISSUE TITLE
API for profiling non-Java apps

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#751]
### Background

async-profiler was designed for profiling JVM processes. Unlike traditional Java profilers, it monitors non-Java threads (e.g., GC threads) and also shows native frames in Java stack traces. async-profiler parses symbols from shared libraries and uses DWARF info for stack walking. Basically, async-profiler can already do much of what can be expected from a non-Java profiler.

### Proposal

Given that async-profiler already deals with non-Java threads, it should be possible to make it work for C, C++ or Rust applications. Currently there are many dependencies on the JVM runtime in the code. The idea of this proposal is to factor out all JVM dependencies so that async-profiler will work with processes that have no `libjvm.so` loaded.

Since dynamic attach does work for native applications, the scope of this proposal is limited to the case when profiler is controlled programmatically from the process being profiled. Similarly to the existing Java API, there will be C API for using inside native applications.

### API

```
typedef const char* asprof_error_t;
typedef void (*asprof_writer_t)(const char* buf, size_t size);

// Should be called once prior to any other API functions
void asprof_init();

// Returns an error message for the given error code or NULL if there is no error
const char* asprof_error_str(asprof_error_t err);

// Executes async-profiler command using output_callback as an optional sink
// for the profiler output. Returning an error code or NULL on success.
asprof_error_t asprof_execute(const char* command, asprof_writer_t output_callback);
```

### Notes

All basic functionality remains the same. Profiler can run in `cpu`, `wall` and other perf_events modes. Flame Graph and JFR output formats are supported, although JFR files will obviously lack Java-specific events.

**Comment by apangin** [comment]
An experimental version is available in the [`native-api`](https://github.com/async-profiler/async-profiler/tree/native-api) branch.

**Comment by apangin** [comment]
API and the implementation has been committed.
To use it in a C/C++ application, include [asprof.h](https://github.com/async-profiler/async-profiler/blob/d46d6c67c0a8555a2cbae25ff3b384b15938c869/src/asprof.h).

In addition, async-profiler can now be injected into a native application through `LD_PRELOAD` mechanism:
```
LD_PRELOAD=/path/to/libasyncProfiler.so ASPROF_COMMAND=start,event=cpu,file=profile.jfr NativeApp [args]
```

**Comment by AlJohri** [comment]
Is there any public documentation on using async-profiler for a rust program? I wasn't able to find anything in the [wiki](https://github.com/async-profiler/async-profiler/wiki).

**Comment by apangin** [comment]
@AlJohri It's documented here in the issue. Async-profiler is not promoted as a standlone Rust profiler for end users - instead, it can be used as a library for developing profiling tools on top of it.

There are two ways of using async-profiler for Rust applications, they are mentioned above:
 1. Start profiler programmatically from the application using the [API](https://github.com/async-profiler/async-profiler/issues/751#issue-1718364682);
 2. Run application with the profiler enabled in the [command line](https://github.com/async-profiler/async-profiler/issues/751#issuecomment-1587546709) by means of `LD_PRELOAD` and `ASPROF_COMMAND` environment variables.
