### ISSUE TITLE
Async Profiler is blaming the wrong method

### ISSUE THREAD

**Issue by franz1981** [async-profiler/async-profiler#758]
That could be rephrased too, into: "the JVM doesn't report the right method?" - don't know yet :P

![image](https://github.com/async-profiler/async-profiler/assets/13125299/110c52fc-fbc0-44ed-b31a-a2c4028485d3)

By running https://github.com/franz1981/quarkus-reactive-beer eg from `script` just run `./benchmark -a`
and using 

```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharin
```

The blamed method is likely wrong, see https://github.com/openjdk/jdk19/blob/967a28c3d85fdde6d5eb48aa0edd8f7597772469/src/java.base/share/classes/java/lang/reflect/Method.java#L609

It could be a case of skidding, but -e cycles report the same, and increasing the frequency still won't help too.

Changing JDK version instead seems to help, and switching to 

```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```

![image](https://github.com/async-profiler/async-profiler/assets/13125299/879f0176-71d6-492e-a193-4737fa9f4cf5)

is not even showing it

**Comment by apangin** [comment]
JDK 19 is no longer supported. I tried JDK 20.0.1 and the profile looks sane to me. Please confirm if you see the issue with the latest JDK.

**Comment by franz1981** [comment]
Thanks Andrei, will double check this morning, but any idea why? :O

**Comment by krzysztofslusarski** [comment]
Wild guess: one of:
- https://bugs.openjdk.org/browse/JDK-8305143
- https://bugs.openjdk.org/browse/JDK-8281677
But it's a guess, I didn't validate that theory.

**Comment by franz1981** [comment]
![image](https://github.com/async-profiler/async-profiler/assets/13125299/2a60b1a0-f48a-4239-bbd4-bc8a37abd625)

This is by using JDK 20.0.1 which is way different then what is observed on JDK 17, but given that they are that different runtime, although I cannot say if is "wrong", i don't know if is fully accurate too (nor JDK 17 one TBH).

**Comment by franz1981** [comment]
My point is...there are no tests on async profiler or on the Jdk to detect that the collected trace is not what's expected?

**Comment by krzysztofslusarski** [comment]
@franz1981 I believe @parttimenerd can give some input here how ```AsyncGetCallTrace``` is tested in Hotspot. I believe that async-profiler can do nothing here, it's just a proxy of lie from JVM to end user. 

I know that those bugs looks scary and make our work much harder, but that's the world we are living now. Both perf and eBPF used with perf-map-agent are also vulnerable to those bugs, so there is no alternative right now (instrumentation and safepoint bias "vintage" sampling are even worse IMO). Sorry, all profilers are lying, you just need get used to it :)

**Comment by franz1981** [comment]
This is true, but if I think about the issue about the jmethodID  (which can be just stale and cause more than wrong profile data) it's probably the AGCT in this current form to not be the right tool for the job. I am sure @apangin is aware of it and can give his perspective

**Comment by krzysztofslusarski** [comment]
If we are talking about the future this may be a solution https://openjdk.org/jeps/435, but for now it's just a candidate.

**Comment by franz1981** [comment]
Yep, JB and some DataDog folks raised the point about the jmethodID and concurrent class unloading in some recent Jdk mailing list too

**Comment by parttimenerd** [comment]
> My point is...there are no tests on async profiler or on the Jdk to detect that the collected trace is not what's expected?
And...they are worthy?

There is a single test, but even this test did only test the topmost method before I fixed it. The testing situation is dire.

https://github.com/parttimenerd/trace_validation/ and https://github.com/parttimenerd/trace_tester should improve this in the future.

> If we are talking about the future this may be a solution https://openjdk.org/jeps/435, but for now it's just a candidate.

I'm currently doing my test to get it in and then backport it.

> Yep, JB and some DataDog folks raised the point about the jmethodID and concurrent class unloading in some recent Jdk mailing list too

This is the reason why the JEP 435 doesn't use jmethodIDs anymore.

**Comment by parttimenerd** [comment]
Reflection is something that caused problems before, see https://bugs.openjdk.org/browse/JDK-8302320. I'm surprised how often ASGCT is right, considering the lack of tests. This is one of the reasons for having a properly specified new API.

**Comment by apangin** [comment]
> but any idea why?

I bet it's again a compiler issue related to lost or corrupted during transformation DebugInfo. Given that we can't fix it in JDK 19 anyway, I see no value in spending more time on this.

> so what JDK versions we can fully trust at this point?

Unfortunately, none. Mapping PC addresses back to bytecode indices has always been problematic. This is an area of JIT compiler's responsibility, Java profilers can't do much about this. What can be relied on so far - is the first non-inlined Java method. The top physical frame can be determined reliably, but all virtual (inlined) frames are reconstructed from DebugInfo provided by the JVM.

I see two possible approaches to improving profiling experience:
1) continuously invest in providing more complete and accurate DebugInfo on the JVM side, including C2 fixes, additional tests, etc.
2) add async-profiler feature to collect detailed instruction-level profile.

**Comment by parttimenerd** [comment]
One idea is to tell the user that inlined methods might be wrongly blamed. Especially when we have inlining information on frames in the future, then we could give the user a notion of which frames are certainly correct.

@franz1981 I'm looking forward to use your benchmark in future testing.

**Comment by franz1981** [comment]
Thanks @parttimenerd , it should use `ap-loader` as well and can use a quarkus native version in case; has been designed to NOT be I/O bound, meaning that cpu profiling will matter there.
