### ISSUE TITLE
Configure alternative profiling signal

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#759]
### Background

Async-profiler heavily relies on POSIX signals. In `perf_events` and `itimer` modes, a profiling event triggers delivery of `SIGPROF` to a currently running thread. In `wall` mode, a thread being sampled receives `SIGVTALRM`. Async-profiler assumes the application does not use `SIGPROF` or `SIGVTALRM` for other purposes.

Furthermore, since a signal handler is a global property of a process, it is not possible to run two instances of async-profiler on the same process concurrently. For example, this can be helpful for doing some ad-hoc profiling with a custom configuration while continuous profiling is already running.

### Proposal

Introduce new `signal` argument to override the default profiling signal(s). It can be used to configure continuous profiler to avoid conflict with an ad-hoc profiler.

E.g. `-agentlib:asyncProfiler=start,event=cpu,signal=36` will force async-profiler use `SIGRTMIN+2` instead of `SIGPROF` for CPU profiling.

To change both `cpu` and `wall` signals, we'll use syntax like `signal=36/37`.

**Comment by parttimenerd** [comment]
Couldn't async-profiler detect this and choose other signals automatically? The underlying APIs seem to offer the possibility.

**Comment by apangin** [comment]
What it can detect automatically is whether a signal has a non-default handler. This does not yet tell if a signal is really used, but this could be sufficient in some cases. However, sometimes async-profiler needs to cooperate with an external process, e.g., system-wide eBPF profiling agent. In these cases, the signal should be set explicitly to be in line with what an external agent uses.

**Comment by parttimenerd** [comment]
> What it can detect automatically is whether a signal has a non-default handler.
And maybe warn the user about this fact.

> However, sometimes async-profiler needs to cooperate with an external process, e.g., system-wide eBPF profiling agent. In these cases, the signal should be set explicitly to be in line with what an external agent uses.
But maybe we could by default make it choose its signals automatically and have a setting to set them explicitly. Or have a `signal=auto` option.

**Comment by apangin** [comment]
It's an interesting idea. I'm not sure if it's worth complicating things though.

**Comment by apangin** [comment]
I'm not sure how important it is right now, but it's an interesting idea.

**Comment by parttimenerd** [comment]
When I find time after working on my JEP, I might take a look into this :)

**Comment by apangin** [comment]
I pushed the fix to automatically find an available signal if the default one is already used.
