### ISSUE TITLE
 AsyncGetCallTrace may crash  jvm

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#763]
there is a known issue https://bugs.openjdk.org/browse/JDK-8283849 that the AsyncGetCallTrace could cause jvm crash.

so for lower jvm version , below java 8u352, it is only safe to run lock, alloc (which do not rely on AsyncGetCallTrace).

is my opinion right?

**Comment by apangin** [comment]
Async-profiler has a workaround for this particular JVM bug. It should never encounter a zombie method when using `--cstack dwarf` option. We have been using `cpu` profiling mode continuously on a large fleet of thousands servers, both with older JDK 8 and JDK 17.

If you notice stability issues when running async-profiler, please report back with specific details, and we'll sort it out.

**Comment by zdyj3170101136** [comment]
> Async-profiler has a workaround for this particular JVM bug. It should never encounter a zombie method when using `--cstack dwarf` option. We have been successfully using `cpu` profiling mode continuously on a large fleet of thousands servers, both with older JDK 8 and JDK 17.
> 
> If you notice stability issues when running async-profiler, please report back with specific details, and we'll sort it out.

you meaning is, i should detect the java version and run async profiler with different args?
version lower 8u352, run with --cstack=dwarf.
version 8u352+, run without --cstack=dwarf ?

**Comment by zdyj3170101136** [comment]
> `--cstack dwarf`与所有 JDK 版本一起使用都可以。这也将使本机堆栈跟踪更加详细和准确。

what is the args cstack default value, and if dwarf is not default, why we do not use dwarf as cstack default value?

**Comment by apangin** [comment]
`cstack` has empty default value, that is the compatibility mode with previous versions of async-profiler where DWARF unwinding was not available.

**Comment by krzysztofslusarski** [comment]
Maybe the default should be changed in 3.0 version? Honestly I don't know what compatibility guarantees you want to guarantee, but changing default in major version upgrade should not surprise anyone.

**Comment by apangin** [comment]
@krzysztofslusarski Yes, that sounds reasonable.

**Comment by zdyj3170101136** [comment]
> `cstack` has empty default value, that is the compatibility mode with previous versions of async-profiler where DWARF unwinding was not available.

is only dwarf could handler this problem.

or the other option, like fp, dwarf, lbr could also handle this situation, too?

**Comment by apangin** [comment]
`cstack` option does not solve the problem itself.

Async-profiler has a workaround for `AsyncGetCallTrace` bug, which applies when the profiler successfully unwinds native part of the stack to the first Java frame. `cstack=dwarf` is just the best option here, since it allows for proper unwinding in most cases.

`cstack=dwarf` does not require external files. It parses `GNU_EH_FRAME` program header in memory instead.

**Comment by 243300852** [comment]
> --cstack=dwarf

你好杨杰，我想请教下，在--cstack=dwarf前后，采集的功能是否发生变化
