### ISSUE TITLE
Filter wall clock profiler thread list

### ISSUE THREAD

**Issue by tomershafir** [async-profiler/async-profiler#766]
It may be useful to have a configurable filter for the thread list of the wall clock profiler, in order to allow to manage overhead for [continuous] off-cpu profiling of highly concurrent applications, and have visibility, even if its not complete. All kind of sampling methods may be applied, e.g. random sampling by thread state.

**Comment by apangin** [comment]
Async-profiler already provides two options for filtering threads for wall clock profiling:
1. `filter` command line option to specify a list of OS thread IDs to include in profiling, e.g. `--filter 123-134,158,160`
2. [`addThread`](https://github.com/async-profiler/async-profiler/blob/117594bb4d1ce61b073c8a9cea438b33f3f09c81/src/api/one/profiler/AsyncProfiler.java#L245-L253)/[`removeThread`](https://github.com/async-profiler/async-profiler/blob/117594bb4d1ce61b073c8a9cea438b33f3f09c81/src/api/one/profiler/AsyncProfiler.java#L255-L263) methods of async-profiler's Java API to dynamically change a list of threads being profiled
