### ISSUE TITLE
Allow to profile only specific threads

### ISSUE THREAD

**Issue by quijote** [async-profiler/async-profiler#768]
Async-profiler already allows to profile threads separately with `-t` option. 

In some cases one may be interested only in specific threads, not necessarily the ones that consume the majority of CPU. A list of thread IDs or thread names could be provided via new command line options.

For example an application has the following threads:

| Name      | Thread ID |
| --------- | -----------------|
| producer1 | 1 |
| producer2 | 2 |
| consumer1 | 3 |
| consumer2 | 4 |

The following threads would be profiled:

| Options | Profiled Threads |
| ---------------------- | -----------------|
| `-tid 1`               | 1 |
| `-tid 1,2`             | 1, 2 |
| `-tname 'producer1'`   | 1 |
| `-tname 'producer*'`   | 1, 2 |
| `-tname '*2'`          | 2, 4 |

**Comment by zdyj3170101136** [comment]
you can add the pid ad label into pprof file, and filter stack trace which matching the label.

**Comment by quijote** [comment]
Thank you.

I did not see `--filter` mentioned in the https://github.com/async-profiler/async-profiler/blob/master/README.md. I will give it a try.

Also did not consider that `-I` and `-X` might work for thread names as well. Will try this as well.
