### ISSUE TITLE
On JDK8, converter.jar fails with NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by benjaminballard** [async-profiler/async-profiler#772]
```
java -cp converter.jar jfr2flame input.jfr output.html
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at one.jfr.JfrReader.<init>(JfrReader.java:78)
	at jfr2flame.main(jfr2flame.java:257)
```

This is likely due to the fact I'm using the pre-built distribution, which may have been built with a later JVM. It seems similar to this case:
https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

I was able to convert the same files successfully after building from source with JDK 8.

**Comment by apangin** [comment]
Thanks, the problem is known.
`converter.jar` from 2.10 pre-release does not have this issue.
