### ISSUE TITLE
how to distinguish cpu and wall jfr 

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#773]
i want to start cpu and wall together with jfr format:
```
/home/centos/async-profiler-2.10-linux-x64/bin/asprof -e cpu,wall -o jfr -d 60 -f cpu_wall.jfr 6574
```
and the cpu jdk.ExecutionSample state is STATE_DEFAULT.
the wall jdk.ExecutionSample state would also have STATE_DEFAULT, too!

so how should i distinguish them, cause both of them have state STATE_DEFAULT.

the wall jfr:
```
/home/centos/async-profiler-2.10-linux-x64/bin/asprof -e wall -o jfr -d 60 -f wall.jfr 6574

yangjie05-mac:~ jie.yang05$ jfr print /Users/jie.yang05/Downloads/wall.jfr | grep -n STATE_DEFAULT
636:  state = "STATE_DEFAULT"
16982:  state = "STATE_DEFAULT"
17668:  state = "STATE_DEFAULT"
33762:  state = "STATE_DEFAULT"
```

the async profiler version is 
https://github.com/async-profiler/async-profiler/issues/767#issuecomment-1637108318

i convert the wall event state STATE_DEFAULT callstack into pprof:
![截屏2023-07-20 上午11 25 50](https://github.com/async-profiler/async-profiler/assets/52686065/cd56296d-f8f4-4839-83e1-10c010a10666)
seems most of callstack is in park and epoll wait.

**Comment by apangin** [comment]
`ExecutionSample` events from CPU profiling have state = `STATE_DEFAULT`.
`ExecutionSample` events from Wall clock profiling have state either `STATE_RUNNABLE` or `STATE_SLEEPING`.

Wall clock mode does not produce events with `STATE_DEFAULT`. Please show your .jfr file if you think this works differently in your case.

**Comment by zdyj3170101136** [comment]
what you said is i expected behaviour from the code.
but in production the wall event would also have STATE_RUNNABLE event.
[wall (2).jfr.zip](https://github.com/async-profiler/async-profiler/files/12115593/wall.2.jfr.zip)


> `ExecutionSample`来自 CPU 分析的事件具有 state = `STATE_DEFAULT`。 `ExecutionSample`挂钟分析中的事件的状态为`STATE_RUNNABLE`或`STATE_SLEEPING`。
> 
> 挂钟模式不会产生带有 的事件`STATE_DEFAULT`。如果您认为这在您的情况下工作有所不同，请显示您的 .jfr 文件。

**Comment by apangin** [comment]
You have two versions of async-profiler loaded simultaneously:
```
jfr print --events NativeLibrary "wall (2).jfr" | grep asyncProfiler
  name = "/home/centos/async-profiler-2.10-linux-x64/lib/libasyncProfiler.so"
  name = "/home/centos/async-profiler-2.9-linux-x64/build/libasyncProfiler.so"
```
They must be conflicting with each other, since both use the same profiling signal: `SIGPROF` for cpu profiling, `SIGVTALRM` for wall clock profiling.

Recently, I've added a new argument `signal` that can configure which alternative signal to use for profiling. This can help in resolving version conflicts. See #759 for details. In any case, it's better to have only one version of the profiler loaded at a time.
