### ISSUE TITLE
what will --alloc do when java 8?

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#774]
seems that SetHeapSamplingInterval only work for java 11+。
so what would happen when we use java 8?
the --alloc would not useful?
so what is the default value in java 8?

**Comment by apangin** [comment]
Async-profiler uses a different mechanism for allocation profiling on JDK 8. It is a bit less efficient, but still suitable for production profiling. `--alloc` is also supported, assuming the sampling granularity is not less than an average TLAB size.

**Comment by zdyj3170101136** [comment]
> Async-profiler 在 JDK 8 上使用不同的分配分析机制。它的效率稍低，但仍然适合生产分析。`--alloc`假设采样粒度不小于平均 TLAB 大小，也支持。

jdk 11 use  tlab.bytes_since_last_sample_point + size_in_bytes to make 512 kb one sample.
https://github.com/openjdk/jdk11u/blob/a829804de566fb89ad0fe45d242a09db24a5867c/src/hotspot/share/gc/shared/memAllocator.cpp#L227
but in async-profiler, you are using the tlab size to  make 512 kb one sample, the tlab size is much higher than  tlab.bytes_since_last_sample_point.

**Comment by zdyj3170101136** [comment]
and i also suggest implement an probablistic sampler like setheapinterval:
https://github.com/openjdk/jdk11u/blob/a829804de566fb89ad0fe45d242a09db24a5867c/src/hotspot/share/runtime/threadHeapSampler.cpp#L80

**Comment by apangin** [comment]
As I mentioned, `--alloc` values are meaningful for JDK 8 when they are larger than a TLAB size. Smaller sampling intervals are not quite useful for production profiling anyway, as they would incur notable overhead.

I admit there are places for enhancement in allocation profiling on JDK 8, however, it's already good enough for production profiling (customers actually use it). With the rapidly declining popularity of JDK 8, I see little sense in investing in its further improvement.

If you have issues with allocation profiling, please open a new ticket, describing the use case in details and possibly adding a standalone reproducer. Thanks.
