### ISSUE TITLE
add random lock profiler for contended duration < lock interval

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#775]
for now, only contended duration > lock interval's stacktrace would be sampled.

this is not good for we to distinguish those code which  have small contended duration but higher compete times.

in go, it add a probabilistic sampling for contended duration < lock interval.

https://github.com/golang/go/blob/f2d709b76925696396441274afbc1d178555a8e6/src/runtime/mprof.go#L493

**Comment by zdyj3170101136** [comment]
> What problem is it going to solve? Can you provide a realistic example?

if we set lock interval to 10ms.
And object monitor occur with 1ms, but very high time like 10000， it would have big influence to user, but we could not distinguish it.

**Comment by apangin** [comment]
Yes, I understand your hypothetical scenario, but do you have a practical example where a concrete performance issue can be detected with your proposal, but cannot be without?

The meaning of the lock parameter is exactly *not* to show lock occurrences shorter than a threshold.

**Comment by apangin** [comment]
I will close the issue for now, but I'm OK with reopening it if there is sufficient arguments for the change.
