### ISSUE TITLE
Some fields in recorded events don't show nicely in jfr print command

### ISSUE THREAD

**Issue by ocadaruma** [async-profiler/async-profiler#776]
When we print alloc or lock profiles recorded by async-profiler by `jfr print --events` command, it produces output like below:
```
% jfr print --events jdk.JavaMonitorEnter /path/to/async-profiler-profile.jfr | less
...
jdk.JavaMonitorEnter {
  startTime = 2023-07-22T10:05:19.508646833Z
  duration = PT0.00013625S
...
```

In contrast to the profiles recorded by JMC (or `jcmd JFR.start`), which produce pretty-formatted durations like:
```
% jfr print --events jdk.JavaMonitorEnter /path/to/jmc-profile.jfr | less
...
jdk.JavaMonitorEnter {
  startTime = 10:01:53.229
  duration = 46.750 us
...
```

This is because async-profiler doesn't annotate these types with `ContentType`.

- https://github.com/adoptium/jdk17u/blob/jdk-17.0.4.1%2B1/src/jdk.jfr/share/classes/jdk/jfr/internal/tool/PrettyWriter.java#L355
- https://github.com/adoptium/jdk17u/blob/jdk-17.0.4.1%2B1/src/jdk.jfr/share/classes/jdk/jfr/ValueDescriptor.java#L214

To produce readable (and consistent with JMC/JFR) output, it's nice to annotate [these types](https://github.com/adoptium/jdk17u/blob/jdk-17.0.4.1%2B1/src/jdk.jfr/share/classes/jdk/jfr/ValueDescriptor.java#L195-L202) with `ContentType` in async-profiler as well.

What do you think?
If it makes sense, I'm happy to submit a patch.

**Comment by apangin** [comment]
Good catch, thanks.
I committed the fix.

**Comment by ocadaruma** [comment]
Thanks you for the quick fix!
