### ISSUE TITLE
what is the overhead cost in production

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#778]
i want to start the all profiler event in production, here is my config, what is the overhead cost:
```
-e cpu,wall,alloc,lock -i 10ms --alloc 512k --wall 200ms --lock 10ms
```

is there any recommend config?

**Comment by apangin** [comment]
To begin with, the syntax is not quite correct: `-e` argument should specify only one event. `--alloc`, `--lock` and `--wall` enable additional events. So, the correct line would be `-e cpu -i 10ms --alloc 512k --wall 200ms --lock 10ms`.

The profiling overhead highly depends on the nature of the application: its average CPU load, number of threads, allocation rate, etc. The values you've chosen are usually fine for production profiling, but to be safe, I'd start with a more conservative configuration, especially for allocation profiling, e.g. `--alloc 4m`.
