### ISSUE TITLE
[Loom] +DoJVMTIVirtualThreadTransitions scalability issue

### ISSUE THREAD

**Issue by franz1981** [async-profiler/async-profiler#779]
JDK version:
```
JDK 20.0.1, Java HotSpot(TM) 64-Bit Server VM, 20.0.1+9-29
```
Reproducer:
```
package red.hat.puzzles.concurrent;

import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

@State(Scope.Benchmark)
@Measurement(iterations = 5, time = 1)
@Warmup(iterations = 10, time = 1)
@Fork(value = 2, jvmArgsAppend = "--enable-preview")
public class VirtualThreadCreation {

    @Param("10")
    int work;

    @Param("1024")
    int tasks;

    Executor executor;

    @Setup
    public void init() {
        executor = Executors.newVirtualThreadPerTaskExecutor();
    }


    @Benchmark
    public void submitWork() throws InterruptedException {
        var done = new CountDownLatch(tasks);
        for (int i = 0; i < tasks; i++) {
            executor.execute(() -> {
                Blackhole.consumeCPU(work);
                done.countDown();
            });
        }
        done.await();
    }
}
```
Running it with  
```
 --jvmArgs="--enable-preview -XX:+UnlockExperimentalVMOptions -XX:+DoJVMTIVirtualThreadTransitions"
```
And attaching async profiler e3b7bfca227ae5c916f00abfacf0e61291df3a67 as JMH profiler, report these numbers on my Ryzen 7950X@4.5 GHz
```
Benchmark                                (tasks)  (work)   Mode  Cnt    Score    Error  Units
VirtualThreadCreation.submitWork            1024      10  thrpt   10  607.376 ± 11.031  ops/s
```
With flamegraphs:
![image](https://github.com/async-profiler/async-profiler/assets/13125299/9183e1ac-a86e-472c-8d13-2394cb26ca08)

Which both show:
- wrong_method deopt handling (due to some race? Some JDK comment report "We might end up in handle_wrong_method if the callee is deoptimized as we race thru here")
- JVMTI VT transitions being super costy and highly contending on few mutexes (on thread state)

Disabling ap on JMH instead, report:
```
Benchmark                         (tasks)  (work)   Mode  Cnt     Score     Error  Units
VirtualThreadCreation.submitWork     1024      10  thrpt   10  2586.494 ± 223.166  ops/s
```
Adding `-prof perfasm` to the async profiler run shows
```
....[Hottest Regions]...............................................................................
 73.61%     [kernel.kallsyms]  native_queued_spin_lock_slowpath (76 bytes) 
  1.90%     [kernel.kallsyms]  native_queued_spin_lock_slowpath (82 bytes) 
  1.22%     [kernel.kallsyms]  _raw_spin_lock (41 bytes) 
  0.83%     [kernel.kallsyms]  __get_user_nocheck_4 (10 bytes) 
  0.83%             libjvm.so  update_register_map1 (150 bytes) 
  0.77%     [kernel.kallsyms]  try_to_wake_up (154 bytes) 
  0.68%             libc.so.6  pthread_mutex_trylock@@GLIBC_2.34 (116 bytes) 
  0.51%             libc.so.6  __GI___pthread_mutex_unlock_usercnt (112 bytes) 
  0.48%     [kernel.kallsyms]  futex_wake (91 bytes) 
  0.46%             libc.so.6  __GI___lll_lock_wait (54 bytes) 
  0.45%             libc.so.6  pthread_mutex_lock@@GLIBC_2.2.5 (125 bytes) 
  0.34%             libjvm.so  vframeStream::vframeStream (164 bytes) 
  0.34%     [kernel.kallsyms]  futex_wake_mark (59 bytes) 
  0.34%     [kernel.kallsyms]  __futex_unqueue (46 bytes) 
  0.33%     [kernel.kallsyms]  futex_wait (90 bytes) 
  0.32%             libc.so.6  __GI___lll_lock_wake (19 bytes) 
  0.32%     [kernel.kallsyms]  futex_q_unlock (25 bytes) 
  0.31%     [kernel.kallsyms]  psi_group_change (355 bytes) 
  0.30%             libjvm.so  OopMapStream::find_next (66 bytes) 
  0.29%     [kernel.kallsyms]  _raw_spin_lock_irqsave (45 bytes) 
 15.36%  <...other 898 warm regions...>
....................................................................................................
100.00%  <totals>

```
which is indeed related high contention in the mutex(ex) in the JVMTI methods.

perf lock indeed reports that avg time to enter the thread_state lock at https://github.com/openjdk/jdk19/blob/967a28c3d85fdde6d5eb48aa0edd8f7597772469/src/hotspot/share/prims/jvm.cpp#L3964C20-L3964C41 has increased from 3.19 us to 26.76 us (!!!) for each of the FJ threads running the V Threads.

Running the same benchmark using a single thread, obviously, report a negligible performance impact, because no contention is involved.

The wild guess here is that after aquiring the lock on the thread state ap cause the lock to be held from longer time making the other threads to experiment more contention; but I didn't yet dug what's going on there, TBH.

**Comment by franz1981** [comment]
Note:

re


 > wrong_method deopt handling (due to some race? Some JDK comment report "We might end up in handle_wrong_method if the callee is deoptimized as we race thru here")

This part doesn't change when async profiler is in, probably, but I have yet to investigate

**Comment by franz1981** [comment]
I've further investigated and the `wrong_method` handling is still there, regardless async profiler is attached or not: `update_register_map1(ImmutableOopMap const*, frame const*, RegisterMap*)` is reported by perf (and AMD u prof) as a very hot method, and it's indeed used in the call-chain to handle `wrong_method`:
![image](https://github.com/async-profiler/async-profiler/assets/13125299/ffcf53fa-2a1b-4448-ade3-a6c0eaea1e9c)
This seems a Loom issue, instead.

**Comment by franz1981** [comment]
And `perf`, while running the JMH bench without async profiler and `jvmArgs="--enable-preview -XX:+UnlockExperimentalVMOptions -XX:-DoJVMTIVirtualThreadTransitions"`

agree that `handle_wrong_method` isn't happening due to async profiler:
![image](https://github.com/async-profiler/async-profiler/assets/13125299/b42cdb80-3e14-45a5-9a6f-66eb8ccdde7d)

**Comment by parttimenerd** [comment]
With limited understanding: This seems like an inappropriate location for a global lock and can probably lead to serious performance degradation when having many virtual threads.

**Comment by franz1981** [comment]
Yep, I see that DoJVMTIVirtualThreadTransitions it's true by default :"(

To summarize, loom seems to have 2 perf issues here:
- handle_wrong_method
- highly contended vmti thread state global lock

ap is somehow making the contention worse by triggering allocation of thread state while holding the global lock (what I have discovered so far, tomorrow will perform a perf diff and  malloc profiling to be sure of this)

**Comment by apangin** [comment]
@franz1981 Thank you for reporting the issue and looking into it.

Since the flame graph shows only generic JVM TI stuff with no evidence of async-profiler, I did a simple sanity test and ran the benchmark with async-profiler loaded but not enabled. The performance was still bad. Then I created a trivial JVM TI agent that does nothing and verified that the JVM goes crazy with the agent loaded, but runs fine without it. Here is this agent:

```c
#include <jvmti.h>

static void JNICALL ClassLoad(jvmtiEnv* jvmti, JNIEnv* jni, jthread thread, jclass klass) {}

int Agent_OnLoad(JavaVM* vm, char* options, void* reserved) {
    jvmtiEnv* jvmti;
    (*vm)->GetEnv(vm, (void**)&jvmti, JVMTI_VERSION_1_0);

    jvmtiEventCallbacks callbacks = {0};
    callbacks.ClassLoad = ClassLoad;
    (*jvmti)->SetEventCallbacks(jvmti, &callbacks, sizeof(callbacks));
    (*jvmti)->SetEventNotificationMode(jvmti, JVMTI_ENABLE, JVMTI_EVENT_CLASS_LOAD, NULL);

    return 0;
}
```

So, the issue has nothing to do with async-profiler - it's the ridiculously inefficient support for virtual threads in JVM TI. Each time a virtual thread is started/finished/mounted/unmounted, JvmtiThreadState is updated under the global `JvmtiThreadState_lock` mutex.

The reason is, many JVM TI notifications can be enabled/disabled on per-thread basis, even though the feature is almost never used. All notifications are typically enabled/disabled globally, but HotSpot chooses to maintain per-thread state anyway. This approach obviously does not scale with virtual threads.

There is an ["optimization"](https://github.com/openjdk/jdk/blob/2d05d3545c8fe4d9e5ad3cee673fc938f84d1901/src/hotspot/share/prims/jvmtiEventController.cpp#L740-L741) to skip creating a per-thread JvmtiState if none of the "thread filtered" events are enabled. However, the list of "thread filtered" events is pretty wide:
```
static const jlong  THREAD_FILTERED_EVENT_BITS = INTERP_EVENT_BITS | EXCEPTION_BITS | MONITOR_BITS | VTHREAD_BITS |
                                        BREAKPOINT_BIT | CLASS_LOAD_BIT | CLASS_PREPARE_BIT | THREAD_END_BIT |
                                        SAMPLED_OBJECT_ALLOC_BIT;
```
In my trivial example, enabling a global `ClassLoad` callback is enough to trigger this condition, acquire a `JvmtiThreadState_lock` and create a new state for the virtual thread.

**Comment by kuksenko** [comment]
FYI. 
-XX:-DoJVMTIVirtualThreadTransitions option was made to suppress the high overhead when profiling with JVMTI.
Please, turn off JVMTIVirtualThreadTransitions always when you collect profiles.
A better solution is on the way, but not ready yet.

**Comment by franz1981** [comment]
Thanks @kuksenko to have looked into this issue! 
I've noticed that option was enabled by default, but I'm pretty happy to disable it; while, related the IC patching or itable issue which cause `wrong_method` handle to be issued? 
There's already a JDK issue I can link here (for the future myself/others)?
Sadly I have no power to fill JDK issues or I would do it myself :"/

**Comment by kuksenko** [comment]
Oh! Stop.
I missed that: "JDK 20.0.1"
throw new TooOldJavaVersionException(); 

;)

**Comment by kuksenko** [comment]
It's a bunch of issues for this area
https://bugs.openjdk.org/issues/?jql=text%20~%20%22JVMTI%20VTMS%20transitions%22%20ORDER%20BY%20created%20DESC

**Comment by franz1981** [comment]
@kuksenko 

I've tried running the benchmark with `JDK 21-ea, OpenJDK 64-Bit Server VM, 21-ea+32-2482` but getting both the same problems - I can try mainline too in a sec (time to compile it)

**Comment by franz1981** [comment]
Uh thanks go Shipilev exist, I've used `JDK 22-testing, OpenJDK 64-Bit Server VM, 22-testing-builds.shipilev.net-openjdk-jdk-b499-20230725` on https://builds.shipilev.net/openjdk-jdk/ getting both the same errors (JVMTI was expected while I was hoping the one re `wrong_method` to not be there

**Comment by parttimenerd** [comment]
Disabling all assertions manually and running a fastdebug build with `-XX:-DoJVMTIVirtualThreadTransitions` causes a segfault:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe96402907f, pid=291970, tid=291995
#
# JRE version: OpenJDK Runtime Environment (22.0) (fastdebug build 22-internal-adhoc.i560383.jdk)
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 22-internal-adhoc.i560383.jdk, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x1c07f]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x64f
```

So this isn't really a solution.

**Comment by sspitsyn** [comment]
The JVM TI capability `can_support_virtual_threads` is enabled. You can use `-XX:-DoJVMTIVirtualThreadTransitions` option or enable `can_support_virtual_threads` capability but not both. They conflict.

**Comment by apangin** [comment]
> The JVM TI capability can_support_virtual_threads is enabled

@sspitsyn The thing is - nobody enabled `can_support_virtual_threads`. 
It's enough to just add an empty set of capabilities to trigger the above assertion:
```
    jvmtiCapabilities capabilities = {0};
    (*jvmti)->AddCapabilities(jvmti, &capabilities);
```

**Comment by sspitsyn** [comment]
@apangin I'm interested to know if disabling (not enabling) this capability helps in this particular case.
The experimental flag -XX:-DoJVMTIVirtualThreadTransitions is just a temporary work around.
We still have a plan/task to support virtual threads in JVM TI in a scalable way. It will take some time though.

**Comment by franz1981** [comment]
@sspitsyn and what about the  `wrong_method_handle` behaviour? is it expected (a bit OT, sorry @apangin )

**Comment by sspitsyn** [comment]
> @sspitsyn and what about the wrong_method_handle behaviour? is it expected (a bit OT, sorry @apangin )

Do you meant `handle_wrong_method` not  `wrong_method_handle`, right?
I have no idea yet.

**Comment by franz1981** [comment]
yep @sspitsyn :"/ 
Looking how the continuation's enterVirtual is natively compiled seems an expected path, while usually it happens due to some deopt or race during IC patching (and i'm not getting any weird compilation logs re Continuation::enter either..) but anyway, I won't go to much OT: re this issue (for ap and any profiler running as an agent, at this point) we have already said the most that's needed.

**Comment by apangin** [comment]
- I created [JDK-8313656](https://bugs.openjdk.org/browse/JDK-8313656) to track the assertion failure.
- Also found [JDK-8308614](https://bugs.openjdk.org/browse/JDK-8308614) related to the very same scalability issue.

As we have relevant JBS issues filed, I think we can resolve this one.
