### ISSUE TITLE
Async-Profiler with bpf client

### ISSUE THREAD

**Issue by AsherAroussi** [async-profiler/async-profiler#780]
Hi.
I download the branch of Async-Profiler that supports bpf client however, I can't find the way to run it.
It looks like the code supports in 'cloud' argument but profiler.sh doesn't.

Link to git version: https://github.com/async-profiler/async-profiler/tree/bpfclient

Can anyone assist ?

**Comment by apangin** [comment]
The version in this branch is not intended for end users.
It does not provide any additional functionality not already available in `master`.
