### ISSUE TITLE
profiler.sh file is missing

### ISSUE THREAD

**Issue by praveennish** [async-profiler/async-profiler#781]
I have used async profiler earlier with profiler.sh for flamegraph. This file is missing but README file contains documentation for profiler.sh. This is confusing

**Comment by AsherAroussi** [comment]
Download async-profiler-2.9-linux-x64

**Comment by praveennish** [comment]
Thanks! I have downloaded the aforesaid package. while I ran profiler.sh command 
./profiler.sh -d 60 -f /tmp/flamegraph.html PID 
it fails with error message 
"Failed to inject profiler into PID"

**Comment by apangin** [comment]
The README refers to the latest release 2.9, which has `profiler.sh` as a launcher.
In the current version being developed, `profiler.sh` has been replaced with the binary launcher `asprof` - see #724 for details. In most cases, profiler commands will work with `asprof` just the same way as they did with `profiler.sh`.

As to "Failed to inject profiler" message, it is described in the [Troubleshooting](https://github.com/async-profiler/async-profiler#troubleshooting) section in README. You can also find a number of previous discussions here among github issues. If you profile a containerized application, make sure the container can access profiler library at the same path as on the host. On Alpine Linux, you may also need to install `libstdc++` package.
