### ISSUE TITLE
why cpu event would have park unpark function?

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#786]
i use async profiler to get cpu event.
and tran it to pprof.
the result shows most of the cpu costed in park.
is this correct?

![截屏2023-08-02 下午4 00 05](https://github.com/async-profiler/async-profiler/assets/52686065/202ba465-94d9-4b8b-b8c3-6240f28994e9)

**Comment by apangin** [comment]
Unfortunately, I can't provide support for third party software (pprof) on async-profiler github.
To inquire about profiling results, please provide the original async-profiler's recording in .jfr format.

**Comment by zdyj3170101136** [comment]
> Unfortunately, I can't provide support for third party software (pprof) on async-profiler github. To inquire about profiling results, please provide the original async-profiler's recording in .jfr format.

file: [cpu (2).jfr.zip](https://github.com/async-profiler/async-profiler/files/12238990/cpu.2.jfr.zip)

jfr print:
```
jdk.ExecutionSample {
  startTime = 2023-08-02T10:15:00.250261066Z
  sampledThread = "Log4j2-TF-1-AsyncLogger[AsyncContext@5d099f62]-1" (javaThreadId = 12)
  state = "STATE_DEFAULT"
  stackTrace = [
    libpthread-2.17.so;649be141 (deleted).pthread_cond_timedwait() line: 0
    libjvm.so.Unsafe_Park() line: 0
    sun.misc.Unsafe.park(boolean, long) line: 0
    java.util.concurrent.locks.LockSupport.parkNanos(Object, long) line: 215
    java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) line: 2078
    com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(long, Sequence, Sequence, SequenceBarrier) line: 38
    com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) line: 56
    com.lmax.disruptor.BatchEventProcessor.processEvents() line: 159
    com.lmax.disruptor.BatchEventProcessor.run() line: 125
    java.lang.Thread.run() line: 748
  ]
}
```

**Comment by apangin** [comment]
I see only 5 execution samples in your .jfr profile, 2 of them coming from `sun/misc/Unsafe.park`, which looks fine, considering that `awaitNanos` is called in a loop. The kernel part of the stack trace (ending with `finish_task_switch`) confirms the CPU time is  spent on context switching caused by thread parking.

**Comment by apangin** [comment]
Right - it's not uncommon for park/unpark to take much CPU resources, for example, see #174 and #577.

In this case, however, pprof graph looks suspicious: normally, cpu profile does not show `AsyncGetCallTrace` - so, it's obviously not a pure cpu profile.
