### ISSUE TITLE
Add total frame count table (across stack traces)

### ISSUE THREAD

**Issue by tomershafir** [async-profiler/async-profiler#799]
To catch a shared module bottleneck called from multiple code paths, like grafana pyroscope:

<img width="1606" alt="Screen Shot 2023-08-15 at 18 57 41" src="https://github.com/async-profiler/async-profiler/assets/86107951/518f5c61-84f3-41ac-9336-01eebef38b21">

**Comment by apangin** [comment]
Thank you for the proposal.
Doesn't `-o tree --reverse` already provide the same?

<img width="545" alt="tree-reverse" src="https://github.com/async-profiler/async-profiler/assets/1749416/4006b6f8-714f-4586-87ee-d6a4b5b97b0f">

**Comment by tomershafir** [comment]
You may have multiple different code paths which contains a frame, which seems not heavy because it is narrow in each path, however the sum of weights form the bottleneck. I dont see how a tree help, its still trace oriented data.

**Comment by zdyj3170101136** [comment]
> You may have multiple different code paths which contains a frame, which seems not heavy because it is narrow in each path, however the sum of weights form the bottleneck. I dont see how a tree help, its still trace oriented data.

use go tool pprof to open it

**Comment by tomershafir** [comment]
oh, its a table. looks legit, thx

**Comment by apangin** [comment]
> You may have multiple different code paths which contains a frame, which seems not heavy because it is narrow in each path, however the sum of weights form the bottleneck. I dont see how a tree help, its still trace oriented data.

It is not the tree format that helps, but the `--reverse` option. It does exactly what you are talking about - merges different code paths to the hottest leaf methods and shows their total percentage. `--reverse` works with the flame graph, too.
