### ISSUE TITLE
asprof output is empty when profiling a container from a host

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#800]
both in pod and in host have async-profiler:
```
/home/data/software/parca-agent/async-profiler-2.10-linux-x64/bin
```

start async-profiler in host to record pod is success.

get async-profiler status in pod is success:
```
sh-4.2# ./asprof status 1
Profiling is running for 17126 seconds
```

but get async-profiler status in host is output nothing:
```
./asprof status pid
```

**Comment by apangin** [comment]
This is the same issue with path translation we discussed in #791.
We're aware of the bug and will likely fix it by the next release.

**Comment by apangin** [comment]
The fix has been committed.

**Comment by apangin** [comment]
Closing the issue as solved. Feel free to reopen if you have further comments.
