### ISSUE TITLE
why async-profiler cpu event less than perf

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#801]
i started perf and async-profiler on same process.
the higher line is perf and lower line is async profiler:
![截屏2023-08-16 下午6 33 25](https://github.com/async-profiler/async-profiler/assets/52686065/7e948594-c46a-4680-a59e-db967e710a38)
and sees async-profiler always less than perf.

the perf result:
![截屏2023-08-16 下午6 32 13](https://github.com/async-profiler/async-profiler/assets/52686065/cd2e6391-33f7-484f-88d4-d5a71f5a6fc5)

the async profiler result:
![截屏2023-08-16 下午6 32 41](https://github.com/async-profiler/async-profiler/assets/52686065/8a13ea98-0780-4c88-854d-6a0d5f741969)

**Comment by apangin** [comment]
Attached graphs are not helpful to me, sorry.
To provide a context for your question, please specify what commands you run, what results do you expect, and what you get instead. Please also mention versions of the used sofware (OS, JDK, async-profiler).

**Comment by zdyj3170101136** [comment]
> 抱歉，附图对我没有帮助。 要为您的问题提供上下文，请指定您运行的命令、您期望的结果以及您得到的结果。另请提及所使用软件的版本（操作系统、JDK、async-profiler）。

async-profiler command:
```
/home/data/software/parca-agent/async-profiler-2.10-linux-x64/bin/asprof collect -d 59 -o jfr --cstack dwarf -f /tmp/25215.jfr -e cpu -i 10ms --alloc 524288 --wall 200ms --lock 10ms 25215
```

i try two type of perf command, the first only perf the process:
```
perf record -a -B -g -F 100 --pid 25215 sleep 59s
```

the other perf all process and get pid result from it:
```
perf record -a -B -g -F 100  sleep 59s
```

in first type, the perf result is a litter higher then async-profiler, most on function attach_listener.

in second type, sometimes the perf result would much higher than async-profiler.

most on function unsafeParkHook

**Comment by zdyj3170101136** [comment]
here is perf script output, seems the unsafe park trigger by libAsyncprofiler.so.

![截屏2023-08-17 下午4 55 25](https://github.com/async-profiler/async-profiler/assets/52686065/2c59cdfe-8dd5-45a7-a46f-578d68c7924a)

seems that start and stop async-profiler itself would cost much of cpu.

**Comment by zdyj3170101136** [comment]
after remove wall type of async profiler.

the cpu cost is much is return to normal.

**Comment by franz1981** [comment]
What happen if you lower the interval for wall to the default value: --wall 200ms seems pretty high here

**Comment by apangin** [comment]
> expect behaviour
perf should only a litter higher than async-profiler.

What exactly do you compare and how do you do that?

**Comment by franz1981** [comment]
@zdyj3170101136 another important consideration:
async profiler -e cpu is using (in perf record) -e cpu-clock events and sadly `perf report --stdio` report the wrong number of events (probably some bug on perf report?).

**Comment by apangin** [comment]
@franz1981 When `--total` option is specified, async-profiler also records the counter value: nanoseconds/cycles/instructions/etc. - what you call "weight". But if we assume that perf interrupts are fair, it should not really matter whether we measure samples or counter values - the ratio will remain the same.

It's still not clear to me what OP compares, so I can't really comment on that.

As a side note: I often see people using `perf -F` option which I consider harmful, as it causes frequent PMU reconfiguration and thus extra overhead (hardware does not sample at a given frequency, only at a given period, therefore kernel needs to constantly adjust sampling period to keep the desired frequency).

`perf -c` provides just as good profiles, but with lower overhead. async-profiler's sampling mode is similar to `perf -c`.

**Comment by franz1981** [comment]
Thanks @apangin for the clarification, I didn't knew that --total would have used the configured period to make the absolute values to match what SVG flamegraphs produced out of perf data does!

For 

> as it causes frequent PMU reconfiguration and thus extra overhead 

Fully agree, looking at the kernel code, HW events indeed require adjustments for each counter overflow (and during throttling too, it seems, which make sense).
But cpu-clock, which is SW it doesn't appear, and the period is fixed and computed just the very first time, at https://github.com/torvalds/linux/blob/93f5de5f648d2b1ce3540a4ac71756d4a852dc23/kernel/events/core.c#L11049-L11052

> perf -c provides just as good profiles

I tends to agree, although HW events which does have correlation with the processor frequency and running on wildly tuned machines (I usually use tuned with network latency profiles, fixed frequencies, etc etc for sake of avoiding frequency fluctuations and/or weird processor idle states...but the world have plenty of unconfigured HW) could benefit from perioding re-evaluation of period, or they won't have uniform distribution...
Thanks for the detailed answer and I hope this digression not to be too much OT: the user has indeed provided not enough info to get any complete answer, just guesses...

**Comment by apangin** [comment]
@zdyj3170101136 Do you have anything to add wrt. to the question or can I close the issue?
