### ISSUE TITLE
Is async-profiler support Virtual Thread?

### ISSUE THREAD

**Issue by Holmesus** [async-profiler/async-profiler#802]
Is async-profiler support Virtual Thread? I used async-profiler profiling an application with virtual thread.
command i used:
sh profiler.sh start -e wall -f a.jfr pid 
sh profiler.sh stop -e wall -f a.jfr pid 
But thread name of event is always the carrier thread's.
May JVM not support or async-profiler ?

**Comment by apangin** [comment]
Async-profiler operates on the level of real (OS) threads. It does not provide details on virtual threads.

**Comment by Holmesus** [comment]
> apangin

thanks！Will async-profiler plan to support？

**Comment by apangin** [comment]
There are plans, but without specific timeline.

**Comment by apangin** [comment]
Closing the issue as answered. Feel free to reopen if you have further questions.
