### ISSUE TITLE
The "--loop" option can't work when combined with the "--fdtransfer" flag.

### ISSUE THREAD

**Issue by zhyee** [async-profiler/async-profiler#803]
When I use the command `./profiler.sh -e cpu,alloc,lock -o jfr --loop 60s -f %n{10000}.jfr --fdtransfer 407234` to profile my jvm process，the profiler output only one file and then stopped. I find that this is caused by the function "single_pid_server" in "fdtransferServer.cpp" source file, because it handle only one connection and then exit immediately,  the subsequent connection  from the profiler will be refused.
Is there any idea to avoid it.

The captured log is like below:
```
[WARN] FdTransferClient connect(): Connection refused
[ERROR] VM::restartProfiler fail: Failed to initialize FdTransferClient
```

**Comment by apangin** [comment]
Thank you for the report.
This configuration is not yet supported. We'll see if we can fix that in one of the next releases.

**Comment by apangin** [comment]
The fix has been pushed.
