### ISSUE TITLE
JMX doesn't generate flamegraph

### ISSUE THREAD

**Issue by insdami** [async-profiler/async-profiler#804]
Hi,
I'm trying to run async-profiler 2.9 remotely as suggested [here](https://github.com/async-profiler/async-profiler/discussions/496). 

![image](https://github.com/async-profiler/async-profiler/assets/1742610/0b1813ee-2ffb-4c13-8058-fe6274780899)

Once I was able to see `AsyncProfiler` listed in the MBeans, I tried to run it using the `execute` operation with the args `start,cpu=event,file=/tmp/flame.html`.

The operation seems to have been accepted, however there was no file flamegraph in `/tmp/`. The only way I could produce a flamegraph file was by just running `execute` with `file=<path>` excluding the `start` argument.

I don't know if this is intended, as in I should run `start` and then produce flamegraph myself on demand by running `execute` or there is a better way to do it.

Thanks

**Comment by insdami** [comment]
Thanks @apangin 

Generating the JFR file works just fine, unfortunately when I run `stop,file=/tmp/flame.html` generates an empty html file. I can produce flamegraph files by just running `execute` with `file=/tmp/flame.html`. Not sure if there is any difference or the outcome is the same.

**Comment by apangin** [comment]
To get a profile (in either format), you need to execute `start`, then wait for some time while profiler is running, and finally execute `stop`.

For `jfr` format, `file` argument should be set in `start` command; for other formats, `file` has effect with `stop` or `dump`. If `file` is specified without an explicit action, then `dump` action is assumed.

It will not be an error to specify `file` both for `start` and `stop`. E.g., the following sequence should work fine both for JFR output and a flame graph:

```java
execute("start,event=cpu,file=/tmp/flame.html");  // or /tmp/profile.jfr
// wait 30 sec
execute("stop,file=/tmp/flame.html");             // or /tmp/profile.jfr
```

**Comment by apangin** [comment]
I assume the question is answered.
Feel free to reopen the issue if you have further comments.
