### ISSUE TITLE
Crash in Profiler::getJavaTraceAsync on OpenJDK 64-Bit Server VM Zulu11.63+52-SA

### ISSUE THREAD

**Issue by Jongy** [async-profiler/async-profiler#807]
Hi Andrei! We've hit this crash in a customer's environment. I extracted some of the details from the hserr file, let me know if any other particular sections could be helpful.

```
# JRE version: OpenJDK Runtime Environment Zulu11.63+52-SA (11.0.18+1) (build 11.0.18.0.102+1-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.63+52-SA (11.0.18.0.102+1-LTS, mixed mode, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x1499d]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x5ed

Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libasyncProfiler.so+0x1499d]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x5ed
C  [libasyncProfiler.so+0x17203]  Profiler::recordSample(void*, unsigned long long, EventType, Event*)+0x3c3
C  [libasyncProfiler.so+0x181ed]  PerfEvents::signalHandler(int, siginfo*, void*)+0xdd

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000100000012
 
7f4e64406000-7f4e64448000 r-xp 00000000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
7f4e64448000-7f4e64647000 ---p 00042000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
7f4e64647000-7f4e64648000 r--p 00041000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
7f4e64648000-7f4e64649000 rw-p 00042000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
```

This is the async-profiler build used in gProfiler, it's running [this](https://github.com/Granulate/async-profiler/tree/v2.10g2) code version that is based on 2.10, and I attached the binary that was actually used for your convenience. [async-profiler.tar.gz](https://github.com/async-profiler/async-profiler/files/12427575/async-profiler.tar.gz).
This is not an area we've modified in gProfiler so I suppose the problem exists in vanilla async-profiler as well.

**Comment by apangin** [comment]
Hi @Jongy,
Register values from `hs_err.log` would be helpful.
In any case, I believe the issue has been already solved in the up-to-date version in master.

The crash has happened while trying to get the receiver class name for itable/vtable stub (see #736). I had a couple of fixes in this area: https://github.com/async-profiler/async-profiler/commit/7a52d79b16e36e1395e29113d915e5d895a46bdd and https://github.com/async-profiler/async-profiler/commit/25587664abea61cec00a116d4d732effe7a67904, but now the feature is disabled by default. It can be enabled back by `-F vtable` option.

As an immediate workaround, you may disable vtable targets in your profiler version with `--safemode 0x40` bit.

**Comment by Jongy** [comment]
Thanks! We'll give it a try with disabled `VTABLE_TARGET`, then.

I'll send you the register values if the crash continues to trigger.

**Comment by 243300852** [comment]
Hello, I have the same problem. I want to know under which conditions this problem occurs, such as operating system type, JDK type, etc.

**Comment by 243300852** [comment]
> Hi Andrei! We've hit this crash in a customer's environment. I extracted some of the details from the hserr file, let me know if any other particular sections could be helpful.
> 
> ```
> # JRE version: OpenJDK Runtime Environment Zulu11.63+52-SA (11.0.18+1) (build 11.0.18.0.102+1-LTS)
> # Java VM: OpenJDK 64-Bit Server VM Zulu11.63+52-SA (11.0.18.0.102+1-LTS, mixed mode, g1 gc, linux-amd64)
> # Problematic frame:
> # C  [libasyncProfiler.so+0x1499d]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x5ed
> 
> Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
> C  [libasyncProfiler.so+0x1499d]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x5ed
> C  [libasyncProfiler.so+0x17203]  Profiler::recordSample(void*, unsigned long long, EventType, Event*)+0x3c3
> C  [libasyncProfiler.so+0x181ed]  PerfEvents::signalHandler(int, siginfo*, void*)+0xdd
> 
> siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000100000012
>  
> 7f4e64406000-7f4e64448000 r-xp 00000000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
> 7f4e64448000-7f4e64647000 ---p 00042000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
> 7f4e64647000-7f4e64648000 r--p 00041000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
> 7f4e64648000-7f4e64649000 rw-p 00042000 103:06 949864                    /tmp/gprofiler_tmp/async-profiler-v2.10g2/glibc/libasyncProfiler.so
> ```
> 
> This is the async-profiler build used in gProfiler, it's running [this](https://github.com/Granulate/async-profiler/tree/v2.10g2) code version that is based on 2.10, and I attached the binary that was actually used for your convenience. [async-profiler.tar.gz](https://github.com/async-profiler/async-profiler/files/12427575/async-profiler.tar.gz). This is not an area we've modified in gProfiler so I suppose the problem exists in vanilla async-profiler as well.
Hello, I have the same problem. I want to know under which conditions this problem occurs, such as operating system type, JDK type, etc.

**Comment by apangin** [comment]
@243300852 The condition is using and old version of async-profiler.
