### ISSUE TITLE
memory leak in java 8

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#809]
our java version is 1.8.

and i want to debug our in use callstack ?

i know that async-profiler only support it in java 11+ and only support a range of time memory in use allocation.

is there any recommend way to analyze memory in use allocation callstack?

**Comment by apangin** [comment]
What do you mean by "in use callstack"?
If I understand correctly, you're interested in "live" feature that tracks allocated objects that remain alive by the end of profiling session. Yes, it's supported only in JDK 11+.
For troubleshooting Java memory leaks, I would suggest analyzing heapdumps with [MAT](https://eclipse.dev/mat/) or a similar tool.

**Comment by apangin** [comment]
Closing the issue in the lack of feedback. Feel free to reopen if you have further comments.
