### ISSUE TITLE
Java off heap allocation profiling (with mprotect event) issue

### ISSUE THREAD

**Issue by RoySunnySean007** [async-profiler/async-profiler#814]
Dear experts,

According to https://youtu.be/c755fFv1Rnk, I use `profiler.sh -d <duration> -e mprotect -f <absolute path of html file>  <java pid>` to profile java off-heap object allocation, but interestingly, there are ~50% samples just show `mprotect`. 
My JDK is JDK11, async version is 2.9, and I run java application in container, and set kernel.perf_event_paranoid=1 and kernel.kptr_restrict=0 in the host machine.
Could u please kindly let me know if there is any wrong? Thanks in advance!

```
sh-4.2# ./profiler.sh -v
Async-profiler 2.9 built on Nov 26 2022
Copyright 2016-2021 Andrei Pangin
sh-4.2# ./profiler.sh -d 60 -e mprotect -f /tmp/sample.html 1 
Profiling for 60 seconds
sh-4.2# java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
sh-4.2# 
```

<img width="1676" alt="image" src="https://github.com/async-profiler/async-profiler/assets/32358517/51725657-009b-4c2e-99ba-45927fa61c1b">

**Comment by RoySunnySean007** [comment]
It works, turned out to be GC related. Thanks @apangin !

**Comment by RoySunnySean007** [comment]
Dear @apangin , sorry to interrupt you again...

My previous assumption is GC related, am I right? If possible, could u please kindly let me know how can I correlated these native async profiler sampling to specific functions? Thanks in advance!

There are two parts: deoptimization & _GI_Clone

<img width="1675" alt="image" src="https://github.com/async-profiler/async-profiler/assets/32358517/07e84142-e23b-4ca8-8652-a8e3ca280a3c">
<img width="1677" alt="image" src="https://github.com/async-profiler/async-profiler/assets/32358517/91e7607f-e3cb-481d-b0a0-9c74433608bb">

**Comment by apangin** [comment]
I'm not sure I understand. Neither of these stack traces come from GC.

[This SO answer](https://stackoverflow.com/a/64426619/3448419) explains how to find cause of deoptimization. In any case, I don't think deoptimization relates to off-heap memory leak. From your profile, netty buffers are more likely suspect.

**Comment by RoySunnySean007** [comment]
Thanks @apangin for ur clear explanation with [SO answer](https://stackoverflow.com/questions/64424775/how-can-i-catch-jits-deoptimization-events-like-unstable-if-with-jnijvmti/64426619#64426619)!
