### ISSUE TITLE
SIGBUS error on Apple M1 Pro VenturaOS

### ISSUE THREAD

**Issue by ahmadkkhaled** [async-profiler/async-profiler#817]
Running the latest release [async-profiler-2.9-macos.zip](https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-macos.zip) of async-profiler for macOS x64/arm64 fails with a SIGBUS error as of recent.

AsyncProfiler used to run perfectly on MoneteryOS, I recently upgraded to VenturaOS and attempting to run async-profiler as  fails with the following error dump (omitted some information from the dump for privacy reasons):

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=, pid=1146, tid=8707
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.8.7.1 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (17.0.8+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# v  ~StubRoutines::SafeFetch32
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
#

```

### System Information

1. Macbook Pro Apple M1 Pro 32 GB running Ventura 13.5.2
2. JRE/JVM: Corretto 17.0.8.7.1

**Comment by apangin** [comment]
This is the same issue as #747
The JVM bug [JDK-8307549](https://bugs.openjdk.org/browse/JDK-8307549) has been fixed by [JDK-8312088](https://bugs.openjdk.org/browse/JDK-8312088) in JDK 17.0.9.
Also, the workaround was implemented in async-profiler - please try the latest version from master.

**Comment by apangin** [comment]
For your convenience, I'm attaching macOS binaries with the fix
[async-profiler-3.0-ea-macos.zip](https://github.com/async-profiler/async-profiler/files/12647822/async-profiler-3.0-ea-macos.zip)

**Comment by Kavindu-Dodan** [comment]
@apangin any idea on when we can expect an official release of the fixed version?

**Comment by apangin** [comment]
@Kavindu-Dodan New release is being prepared. There is no specific date.
