### ISSUE TITLE
Some native traces truncated

### ISSUE THREAD

**Issue by rshkv** [async-profiler/async-profiler#829]
I'm looking at a flame graph with some traces looking truncated. I was hoping someone has tips to profile those missing frames.

<img width="2511" alt="Screenshot 2023-10-19 at 20 19 26" src="https://github.com/async-profiler/async-profiler/assets/7870972/307f50cb-66da-4e3e-b11a-1a98d1a95b41">

The profile is recorded using a runtime-attached `async-profiler` (`AsyncProfiler.getInstance().execute(...)`). I'm using `event=itimer` because this is running inside a container.

[truncated.html.zip](https://github.com/async-profiler/async-profiler/files/13046903/truncated.html.zip)

**Comment by apangin** [comment]
By default, async-profiler relies on frame pointer for unwinding native frames. However, this will not work if a native library is compiled with `-fomit-frame-pointer` optimization. 

Please try `--cstack dwarf` option to enable DWARF-based stack unwinding. See #215 for details.

**Comment by rshkv** [comment]
`dwarf` worked like a charm! Thank you very much.

![Screenshot 2023-10-20 at 12 07 24](https://github.com/async-profiler/async-profiler/assets/7870972/048e4cff-128e-4158-96d8-5374b87dad8d)
