### ISSUE TITLE
Add time-to-safepoint JFR event

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#833]
### Background

One of async-profiler features is time-to-safepoint profiling (`--ttsp` option) which enables collection of CPU or wall-clock events only in the time window between a safepoint has been requested and all Java threads have been stopped. This helps to diagnose the cause of long time-to-safepoint pauses.

`--ttsp` option is the most useful with JFR output format, since it preserves all samples with timestamps in a way that they can be matched with the corresponding pauses. However, to trace these pauses, user needs to enable safepoint logging and then manually match JFR samples with the VM logs.

It would be helpful to emit an additional JFR event for each time-to-safepoint pause to make it possible to analyze pauses using only the profiler recording independently of the VM logs.

### Proposal

Introduce new event in async-profiler recordings for time-to-safepoint pauses. In fact, this event can be generalized for any combination of `--begin/--end` triggers, not just for safepoints.

### Implementation

Add `profiler.Window` JFR event with the following fields:
 - startTime
 - duration
 - eventThread

It will be emitted for every time window between `--begin` and `--end` traps. In particular, for `--ttsp` feature, each `profiler.Window` event will correspond to the time interval between the execution of `SafepointSynchronize::begin` and `RuntimeService::record_safepoint_synchronized` functions - in other words, each event will denote a corresponding time-to-safepoint pause.

**Comment by apangin** [comment]
In this example, we see that a `Profiling Window` event with the duration of 32 ms is followed by 4 `Method Profiling Sample` events all with the same stack trace ending with `MonitorList::unlink_deflated`.

<img width="512" alt="jfr" src="https://github.com/async-profiler/async-profiler/assets/1749416/3fb5756e-44dd-4aca-b9a8-cb66e55da57e">

The above information suggests that the long time-to-safepoint pause (32 ms) was caused by the VM code doing monitor deflation. This already helped us to diagnose [JDK-8319048](https://bugs.openjdk.org/browse/JDK-8319048).

**Comment by richardstartin** [comment]
Hi @apangin, just for future reference, how does this differ from `jdk.SafepointBegin` (to get the timing) and `jdk.VMOperation` (to get the operation name) events? Unless I'm mistaken, `jdk.SafepointBegin` includes the [time to suspend threads](https://github.com/openjdk/jdk/blob/4a85f6ae9f0381f0e29160fb1d304d7bde5840ba/src/hotspot/share/runtime/safepoint.cpp#L355C23-L355C34). Is this just in case the user wants to use async-profiler without any built in JFR events at all?

**Comment by franz1981** [comment]
I think there's some overlap here as @richardstartin noted, but the `profiler.Window` generic name is probably there to cover for other types (user-defined) begin/end traps cases too, which ttsp is just an handy shortcut. 
Said that, I didn't verified (in the jdk src) when safepoint begin is emitted, but according to its name it's likely the same as profilerWindow's ttsp

**Comment by apangin** [comment]
You are both right. First, as the description says, this is a generic event that works for any user-defined `begin`/`end` trigger. Second, enabling JDK Flight Recorder at runtime for the first time may have a significant performance impact, so it's better to stay with async-profiler-only events if they are sufficient to solve the problem.

Strictly speaking, the feature does not add anything fundamentally new - it's just a matter of convenience.

**Comment by richardstartin** [comment]
It might be difficult to implement here because it requires state and context propagation to do it, but we (Datadog continuous profiler) record things like times spent in thread pool queues with latency thresholds so you can see what else was executing immediately before on the thread your task ends up running (i.e. blocking tasks clogging up event loops). E.g. in the screenshot below a "mouse" task gets stuck behind an "elephant" and has to wait.
<img width="1318" alt="Screenshot 2023-11-02 at 11 28 54" src="https://github.com/async-profiler/async-profiler/assets/16439049/f76d8c4e-98c6-4d17-b5c8-d509a217b140">

I wonder if this event could be generalised slightly so a user could instrument their code (either with a java agent or manually) to trace events across thread boundaries to produce similar traces?

**Comment by apangin** [comment]
@richardstartin What you propose is definitely an interesting feature, although it has no direct relationship with the original problem. Feel free to create a new issue, and let me close this one as completed. Thanks.
