### ISSUE TITLE
Dear Andrei, when will we release 2.10?

### ISSUE THREAD

**Issue by RoySunnySean007** [async-profiler/async-profiler#848]
Dear @apangin ,

Starting from 2.10, we will use asprof binary instead of profiler.sh, which is very amazing!!!
May I ask when will we release 2.10 (currently it is in pre-release stage)? I am glad to contribute if permitted. 

Thanks,
Roy

**Comment by apangin** [comment]
There will be no 2.10 version.

The next release is 3.0 with a [considerable list of changes](https://github.com/async-profiler/async-profiler/blob/master/CHANGELOG.md#30---early-access). I don't have an exact date for the release - likely by the end of the year.

In the mean time, you may try out the Early Access binaries:
 - for Linux x64 / glibc: https://profiler.tools/builds/async-profiler-3.0-ea-linux-x64.tar.gz
 - for Linux x64 / musl: https://profiler.tools/builds/async-profiler-3.0-ea-linux-musl-x64.tar.gz

**Comment by RoySunnySean007** [comment]
Thanks so much @apangin!  Compared with 2.10, do you recommend that I need to use 2.10 or 3.0-ea in our production? 

Thanks!
Roy

**Comment by apangin** [comment]
3.0-ea is more mature and is closer to the upcoming release.

**Comment by RoySunnySean007** [comment]
Thanks so much for ur kindly suggestion, @apangin ! Hope we will have 3.0 official release soon, "#795: AsyncGetCallTrace replacement" will be huge milestone in java profiling history!

**Comment by zdyj3170101136** [comment]
latest release:
[async-profiler.tar.gz](https://github.com/async-profiler/async-profiler/files/13856770/async-profiler.tar.gz)

**Comment by nobeh** [comment]
@zdyj3170101136 Any chance there's also an updated EA release fo MacOS M1? Thanks

**Comment by RoySunnySean007** [comment]
@zdyj3170101136 , latest release means latest ea release?

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136，最新版本是指最新的EA版本吗？

yes, include the issue https://github.com/async-profiler/async-profiler/issues/873
