### ISSUE TITLE
Thread filter in wallclock

### ISSUE THREAD

**Issue by tanjh0421** [async-profiler/async-profiler#851]
when starting async-profiler in wall mode, it seems easier to put threads that need to be profiled into thread-filter than to find threads that do not need to be profiled during the course of a profiling session. #296 

Is it possible to add a mechanism to collect threads included in the thread filter?

**Comment by apangin** [comment]
I'm not sure I understand the question. The filter includes only those threads that you've added explicitly: either in `filter` option or via `addThread` API. So why do you need a mechanism to collect such threads, and how are you going to use this information?

**Comment by tanjh0421** [comment]
I'm sorry I didn't make it clear. 
what I'm trying to say is, could wallclock just only send signals to threads in the thread-filter? instead of skipping them

**Comment by apangin** [comment]
> could wallclock just only send signals to threads in the thread-filter

That's exactly how it works now.
