### ISSUE TITLE
Target application crashes during profiling on M1 macbook

### ISSUE THREAD

**Issue by gladko** [async-profiler/async-profiler#853]
trying to profile same simplest app as described in #852 but a little beat longer. 20 seconds instead of 5.
Target app is started from intelliJ/ Gradle runner

Results: target app crashes. 
[hs_err_pid32493.log](https://github.com/async-profiler/async-profiler/files/13513386/hs_err_pid32493.log)

Also tried to attach async-profiler to ZuluMissionControl and profile it. ZMC crashed. 
[hs_err_pid26660.log](https://github.com/async-profiler/async-profiler/files/13513453/hs_err_pid26660.log)

**Comment by apangin** [comment]
The workaround is to use JDK <=11.0.20 or >=17.0.9

**Comment by gladko** [comment]
I'm using JDK 11.0.14. 
Will try 17. Thanks.

**Comment by apangin** [comment]
Both hs_err logs indicate you're running JDK 11.0.21+9.

There is no such issue with JDK 11.0.14. If you happen to see a crash with 11.0.14 - please send a relevant crash dump. Thanks.

**Comment by gladko** [comment]
> Both hs_err logs indicate you're running JDK 11.0.21+9:
Confirm. Started app from intelliJ where 11.0.21 was used.
