### ISSUE TITLE
Dead loop occured when doing perf

### ISSUE THREAD

**Issue by choxsword** [async-profiler/async-profiler#867]
![image](https://github.com/async-profiler/async-profiler/assets/17537282/6baa7d64-0194-40f5-b175-ed0a481e5ffb)

![企业微信截图_17025259212201](https://github.com/async-profiler/async-profiler/assets/17537282/1ee05d83-c68f-4627-ab65-eb509bbeff3f)
![企业微信截图_17025385145680](https://github.com/async-profiler/async-profiler/assets/17537282/41ca6172-858b-481d-b90e-923d93e2ae5a)

The pictures above are generated by pstack and gdb.   The async_profiler is maximizing CPU usage and does not exit.  It seems that there is a spin lock which is not got released, leading to such dead loop issue.

**Comment by apangin** [comment]
What profiler version are you running?
Can you show stack traces of other threads?

**Comment by choxsword** [comment]
> What profiler version are you running? Can you show stack traces of other threads?

version is Async-profiler 2.7 built on Nov 25 2022.   The primary scene has already been lost. So I'm sorry that I cannot provide more informations except the exsisting one.

**Comment by apangin** [comment]
There were many fixes since version 2.7. Please try an up-to-date version of the profiler.
2.7 is no longer supported.

**Comment by apangin** [comment]
I'm closing the bug assuming it has been already fixed. Feel free to reopen if you encounter this again with a recent version.
