### ISSUE TITLE
Random Thread Sampling on Wall Profiling

### ISSUE THREAD

**Issue by tanjh0421** [async-profiler/async-profiler#871]
Can a random sampling capacity (such as the datadog) be added to wall collector and an interface be added to obtain the sampling frequency?

**Comment by apangin** [comment]
If you would like to contribute a new async-profiler feature, I suggest you first describe the problem, provide real-life examples on how the proposed feature addresses this problem, and outline the implementation approach.

**Comment by tanjh0421** [comment]
The current wall profile sends SIGVTALRM signals to all threads. Even if the minimum interval is limited, the CPU usage increases too high.
I see that Datadog uses a pool sampling algorithm to signal only some threads. However, such data is incomplete. To ensure that the data conforms to the actual situation as much as possible, the random rate can be reported at the same time to facilitate the user to calculate the expected value.

**Comment by apangin** [comment]
If the problem you're concerned about is the high overhead of wall-clock sampling with many threads, I have a better idea on how to deal with that. It'll be likely implemented in one of the next versions. Otherwise, I'm open to proposals, bug reports, contributions and pull requests.
