### ISSUE TITLE
[WARN] perf_event mmap failed: Operation not permitted

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#875]
the pid 3990236 is a pod, when i try to profile it from host, i got those error, but there still have profile data.

is the error would have any other influence?
```
 nsenter -t 3990236 --mount --pid /tmp/async-profiler-2.10-linux-x64/bin/asprof 1

[WARN] Kernel symbols are unavailable due to restrictions. Try
  sysctl kernel.perf_event_paranoid=1
  sysctl kernel.kptr_restrict=0
[WARN] perf_event mmap failed: Operation not permitted
[WARN] perf_event mmap failed: Operation not permitted
[WARN] perf_event mmap failed: Operation not permitted
[WARN] perf_event mmap failed: Operation not permitted
[WARN] perf_event mmap failed: Operation not permitted
```

**Comment by zdyj3170101136** [comment]
i create the async profiler file in pid tmp directory.
![截屏2024-01-04 下午6 14 33](https://github.com/async-profiler/async-profiler/assets/52686065/d20cffe4-fbfe-4131-8cba-f1c7bae0d5aa)

**Comment by zdyj3170101136** [comment]
asprof version:
```
./async-profiler-2.10-linux-x64/bin/asprof --version
Async-profiler 2.10 built on Jul 16 2023
Copyright 2016-2023 Andrei Pangin
```

**Comment by yanglong1010** [comment]
This might help [link](https://github.com/async-profiler/async-profiler#:~:text=the%20message%20%22-,perf_event%20mmap,-failed%3A%20Operation%20not)

**Comment by apangin** [comment]
@zdyj3170101136 You don't need to use `nsenter`: when running profiler from the host under a privileged user, `asprof` will switch to proper namespaces automatically. Also, try `--fdtransfer` option - it should solve most of issues with the permissions in a container, including the mentioned "perf_event mmap failed".

Otherwise, if you don't need kernel stack traces, just use `-e ctimer` mode instead of `-e cpu`. This mode does not rely on perf events and therefore you won't face any related warnings.
Note: `-e ctimer` is available since async-profiler 3.0-ea.

**Comment by zdyj3170101136** [comment]
> 链接

it is a privileged daemonSet， but running profiling with no nsenter would output with nothing:
```
[root@iZuf6ahw0qz19tt4pg9gpzZ tmp]# /tmp/async-profiler-2.10-linux-x64/bin/asprof status 3990236
```

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136 You don't need to use `nsenter`: when running profiler from the host under a privileged user, `asprof` will switch to proper namespaces automatically. Also, try `--fdtransfer` option - it should solve most of issues with the permissions in a container, including the mentioned "perf_event mmap failed".
> 
> Otherwise, if you don't need kernel stack traces, just use `-e ctimer` mode instead of `-e cpu`. This mode does not rely on perf events and therefore you won't face any related warnings. Note: `-e ctimer` is available since async-profiler 3.0-ea.

it is a privileged daemonSet， but running profiling with no nsenter would output with nothing:
```
[root@iZuf6ahw0qz19tt4pg9gpzZ tmp]# /tmp/async-profiler-2.10-linux-x64/bin/asprof status 3990236
```

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136 You don't need to use `nsenter`: when running profiler from the host under a privileged user, `asprof` will switch to proper namespaces automatically. Also, try `--fdtransfer` option - it should solve most of issues with the permissions in a container, including the mentioned "perf_event mmap failed".
> 
> Otherwise, if you don't need kernel stack traces, just use `-e ctimer` mode instead of `-e cpu`. This mode does not rely on perf events and therefore you won't face any related warnings. Note: `-e ctimer` is available since async-profiler 3.0-ea.

try 3.0, it could auto find the pid.

but there still have mmap failed error:
```
[root@iZuf6ahw0qz19tt4pg9gpzZ bin]# ./asprof 3990236
[WARN] Kernel symbols are unavailable due to restrictions. Try
  sysctl kernel.perf_event_paranoid=1
  sysctl kernel.kptr_restrict=0
[WARN] perf_event mmap failed: Operation not permitted
[WARN] perf_event mmap failed: Operation not permitted
```

what would happen if it could not perf_event mmap failed?
if it is accessible i would not do more things.

i also notice that the issue [perf_event mmap failed:](https://github.com/async-profiler/async-profiler/issues/701) is fixed!!!

we could load twice in different locations!!!

thanks!

**Comment by zdyj3170101136** [comment]
> 这可能有助于[链接](https://github.com/async-profiler/async-profiler#:~:text=the%20message%20%22-,perf_event%20mmap,-failed%3A%20Operation%20not)

what happen if could not open perf_event mmap, seems there still have lots of callstack output.

```
--- 40208014 ns (0.15%), 3 samples
  [ 0] java.util.concurrent.ConcurrentHashMap.casTabAt
  [ 1] java.util.concurrent.ConcurrentHashMap.putVal
  [ 2] java.util.concurrent.ConcurrentHashMap.put
  [ 3] org.apache.catalina.connector.Request.setAttribute
  [ 4] org.apache.catalina.valves.RemoteIpValve.invoke
  [ 5] org.apache.catalina.connector.CoyoteAdapter.service
  [ 6] org.apache.coyote.http11.Http11Processor.service
  [ 7] org.apache.coyote.AbstractProcessorLight.process
  [ 8] org.apache.coyote.AbstractProtocol$ConnectionHandler.process
  [ 9] org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun
  [10] org.apache.tomcat.util.net.SocketProcessorBase.run
  [11] org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker
  [12] org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run
  [13] org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run
```

**Comment by zdyj3170101136** [comment]
oh, i find i use --cstack dwarf in prod.

so this problem would not happen.

**Comment by apangin** [comment]
> what would happen if it could not perf_event mmap failed?

The answer is in [README](https://github.com/async-profiler/async-profiler#:~:text=Otherwise%20the%20message%20%22perf_event%20mmap%20failed%3A%20Operation%20not%20permitted%22%20will%20be%20printed%2C%20and%20no%20native%20stack%20traces%20will%20be%20collected.)
