### ISSUE TITLE
README refers to "asprof" which is missing from the release

### ISSUE THREAD

**Issue by dsyer** [async-profiler/async-profiler#877]
The README has a lot of examples of using a binary called `asprof` but that doesn't exist any more. I think?

**Comment by vyazelenko** [comment]
@dsyer `asprof` is the name of the binary that `make` will produce (see [Makefile](https://github.com/async-profiler/async-profiler/blob/8910a7a46241abc7cb5b80ba6717c3eab603aae6/Makefile#L6)).
Previously there was a `profiler.sh` script instead which you could still see in the existing release packages.

**Comment by apangin** [comment]
README refers to the latest profiler version from in the `master` branch.
As a result of #724, `profiler.sh` script has been replaced with a binary launcher `asprof`.

An archive with any of the previous releases contains README actual for that particular release.

**Comment by dsyer** [comment]
Understood. That’s helpful. But the README also tells you to download the tarball from the releases. So it’s inconsistent and confusing, at least until there is a new release.

**Comment by apangin** [comment]
New release has been published, and therefore the issue has been resolved.
