### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by mjwSilence** [async-profiler/async-profiler#878]
The thing is, I am using Jprofiler to analyze Java services on Linux servers. Due to network limitations, I can only set up a Windows server in the network environment where the Linux server is located, and then run Jprofiler on this Windows server to analyze Java services on Linux. 
I think this process is quite complicated. If I use async profiler instead of Jprofiler, will there be any changes?

**Comment by apangin** [comment]
A usual (and the simplest) way to use async-profiler is to start it from the command line passing PID of the target Java process. This typically requires ssh access to the host where your Java application runs.

Async-profiler can be also controlled remotely, although this is not quite secure, unless you work in a trusted private network. The options to control async-profiler over a network include:
 - HTTP API, as mentioned [here](https://github.com/async-profiler/async-profiler/issues/512#issuecomment-1107673566);
 - JMX, as discussed [here](https://github.com/async-profiler/async-profiler/discussions/496#discussioncomment-1614455).

**Comment by apangin** [comment]
I assume the question is answered; closing
