### ISSUE TITLE
Option jfrsync breaks jfr2flame with to/from params

### ISSUE THREAD

**Issue by petrbouda** [async-profiler/async-profiler#881]
If I generate JFR output with:
**-agentpath:<path>/libasyncProfiler.so=start,event=ctimer,alloc,jfrsync=default,cstack=vm,file=<path>/with-jfrsync.jfr**
then I the converter output jfr2flame is empty.
**java -jar converter.jar jfr2flame <path>/with-jfrsync.jfr cpu.html --from 10000 --to 50000** (from 10sec to 50sec)

without **jfrsync=default** it works

**Comment by apangin** [comment]
Thank you for the report.
jfr2flame did not handle recordings with heterogeneous chunks correctly.
The workaround was to split the recording into different chunks:
```
jfr disassemble --max-chunks 1 recording.jfr
```

I pushed the fix.

**Comment by petrbouda** [comment]
That was quick! 🙂 thanks a lot!
