### ISSUE TITLE
DWARF symbols not captured for Rust library

### ISSUE THREAD

**Issue by burgerindividual** [async-profiler/async-profiler#883]
I have a rust library compiled with dwarf symbols included, but asprof doesn't seem to be able to read them. On the other hand, perf seems to be able to read them just fine.

`perf record -a -F 997 -p $(pgrep -n -x java) --call-graph dwarf -- sleep 5` output rendered in speedscope
![image](https://github.com/async-profiler/async-profiler/assets/30326913/b225b907-7532-4c24-976e-259afe3783ca)
`asprof -e cpu --cstack dwarf -i 997 -d 5 -o collapsed -t -s $(pgrep -n -x java)` output rendered in speedscope
![image](https://github.com/async-profiler/async-profiler/assets/30326913/ee7a5e9b-4428-41da-97ef-5cf5b70d7fd1)

Here is the library `.so` for further inspection: [link](https://cdn.discordapp.com/attachments/540311565644070923/1202694697185968229/libsodium_core.so?ex=65ce63b8&is=65bbeeb8&hm=cd4f6793a45be5d085970d10679aa2122f0f50f71fc362e855296544333c19b8&)

Here is the collapsed stack output for further inspection: [link](https://cdn.discordapp.com/attachments/540311565644070923/1202695789479071825/test.collapsed?ex=65ce64bd&is=65bbefbd&hm=ff70c8180a7f44f508c24f155240d164f70039a36e2f7deb1efa2eac3ee1308b&)

**Comment by apangin** [comment]
Async-profiler gets symbols from `.symtab` section, whether embedded in a shared library or located in a separate debuginfo file. Async-profiler does not parse `.debug_*` sections.

In your case, `libsodium_core.so` has a trimmed symbol table: check
```
nm libsodium_core.so
```
Therefore, async-profiler shows only limited symbolic information.

**Comment by apangin** [comment]
Please check your compilation options to make sure binaries include a meaningful symbol table (`.symtab` section).
Parsing extended debug information is out of project scope at this point (unless someone wants to contribute that to async-profiler).

**Comment by burgerindividual** [comment]
I don't think using `.symtab` in this case can work ever, as all of the methods seen in the `prof` screenshot that aren't in the `asprof` screenshot are inlined. I think this is probably a reasonable restriction, as it looks like it would be very difficult to obtain the inline method information without effectively using a full DWARF parser, or somehow obtaining that information though a tool that can parse them, like `prof`. It may make sense to document this behavior in the wiki, though.
