### ISSUE TITLE
src/vmEntry.cpp#L107 seems problematicly getting the wrong property java.vm.version

### ISSUE THREAD

**Issue by heoq** [async-profiler/async-profiler#888]
It seems that the correct property should be java.vm.specification.version now?

https://github.com/async-profiler/async-profiler/blob/master/src/vmEntry.cpp#L107

java.vm.compressedOopsMode | Zero based
-- | --
java.vm.specification.vendor | Oracle Corporation
java.vm.specification.name | Java Virtual Machine Specification
java.vm.vendor | Eclipse Adoptium
java.vm.specification.version | 21
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.info | mixed mode, sharing
java.vm.version | 21+35-LTS

**Comment by apangin** [comment]
`java.vm.version` is the intended property. What's wrong with that?

**Comment by heoq** [comment]
@apangin Thanks for the quick response! On the version I mentioned above, running
```
profiler.sh --alloc 500k --live -d 60 <pid> -f test_live.collapsed
```
gave the error:

```
[ERROR] 'live' option is supported on OpenJDK 11+
```

**Comment by heoq** [comment]
I checked with a snippet that
```
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
    printf("%d\n", atoi("21+35-LTS"));
    return 0;
}
```
does return 21. Maybe there is some other reason that I cannot profile live objects on Openjdk21

**Comment by apangin** [comment]
What profiler version do you use?
`profiler.sh` suggests it's not the latest version, because there is no more `profiler.sh` in async-profiler 3.0.

Also, check `grep asyncProfiler /proc/PID/maps` if it contains multiple profiler versions already loaded into the process.

**Comment by heoq** [comment]
Yeah with with async profiler 3.0 in a clean enviroment I get the live alloc profile now. Maybe earlier I missed up some older version installed from the yum repo. Thank you for the help!
