### ISSUE TITLE
Could not set dlopen hook. Unsupported JVM? seems libjvm.dylib lack of 'Section __la_symbol_ptr':

### ISSUE THREAD

**Issue by CarsonLay** [async-profiler/async-profiler#902]
## The libjvm I compiled (macOS 14, x86_64)：

shao@shaodeMini debug % size -x -l -m libjvm.dylib 
Segment __TEXT: 0x179c000 (vmaddr 0x0 fileoff 0)
	Section __text: 0x15397c9 (addr 0x46a0 offset 18080)
	Section __stubs: 0x54c (addr 0x153de69 offset 22273641)
	Section __init_offsets: 0x5704 (addr 0x153e3b8 offset 22275000)
	Section __const: 0x2cbbc (addr 0x1543ac0 offset 22297280)
	Section __cstring: 0x22ad33 (addr 0x1570680 offset 22480512)
	Section __unwind_info: 0xbd0 (addr 0x179b3b4 offset 24753076)
	Section __eh_frame: 0x48 (addr 0x179bf88 offset 24756104)
	total 0x1797920
Segment __DATA_CONST: 0xf4000 (vmaddr 0x179c000 fileoff 24756224)
	Section __got: 0x748 (addr 0x179c000 offset 24756224)
	Section __const: 0xf1050 (addr 0x179c750 offset 24758096)
	total 0xf1798
Segment __DATA: 0xe0000 (vmaddr 0x1890000 fileoff 25755648)
	Section __data: 0x2aa48 (addr 0x1890000 offset 25755648)
	Section __thread_vars: 0x198 (addr 0x18baa48 offset 25930312)
	Section __thread_data: 0x18 (addr 0x18babe0 offset 25930720)
	Section __thread_bss: 0x50 (addr 0x18babf8 zerofill)
	Section __bss: 0x1bfd8 (addr 0x18bac50 zerofill)
	Section __common: 0x96808 (addr 0x18d6c40 zerofill)
	total 0xdd428
Segment __LINKEDIT: 0x1288000 (vmaddr 0x1970000 fileoff 25935872)
total 0x2bf8000

----------------------------------------------------

## Official libjvm：

shao@shaodeMini debug % size -x -l -m ../server/libjvm.dylib
Segment __TEXT: 0xd28000 (vmaddr 0x0 fileoff 0)
	Section __text: 0xc45740 (addr 0x4690 offset 18064)
	Section __stubs: 0x52e (addr 0xc49dd0 offset 12885456)
	Section __stub_helper: 0x8b2 (addr 0xc4a300 offset 12886784)
	Section __cstring: 0x8e53e (addr 0xc4abc0 offset 12889024)
	Section __const: 0x25b44 (addr 0xcd9100 offset 13472000)
	Section __ustring: 0xee (addr 0xcfec50 offset 13626448)
	Section __dof_hotspot_j: 0x12501 (addr 0xcfed3e offset 13626686)
	Section __dof_hs_privat: 0x278 (addr 0xd1123f offset 13701695)
	Section __dof_hotspot: 0x2c35 (addr 0xd114b7 offset 13702327)
	Section __unwind_info: 0x13ee0 (addr 0xd140ec offset 13713644)
	total 0xd2391e
Segment __DATA: 0x168000 (vmaddr 0xd28000 fileoff 13795328)
	Section __nl_symbol_ptr: 0x8 (addr 0xd28000 offset 13795328)
	Section __got: 0x1b8 (addr 0xd28008 offset 13795336)
	Section __la_symbol_ptr: 0x6e8 (addr 0xd281c0 offset 13795776)
	Section __mod_init_func: 0x5600 (addr 0xd288a8 offset 13797544)
	Section __const: 0xd7030 (addr 0xd2deb0 offset 13819568)
	Section __data: 0x295c8 (addr 0xe04f00 offset 14700288)
	Section __thread_vars: 0x198 (addr 0xe2e4c8 offset 14869704)
	Section __thread_data: 0x18 (addr 0xe2e660 offset 14870112)
	Section __thread_bss: 0x4c (addr 0xe2e678 zerofill)
	Section __common: 0x4b458 (addr 0xe2e700 zerofill)
	Section __bss: 0x133c0 (addr 0xe79b60 zerofill)
	total 0x164eb4
Segment __LINKEDIT: 0x410000 (vmaddr 0xe90000 fileoff 14876672)
total 0x12a0000

--------------------------------------------------

how should i fix this?
can '__la_symbol_ptr' be weak dependence?

thanks.

**Comment by apangin** [comment]
What JVM version are you using? From what JDK distribution? What are the steps to reproduce the issue?

**Comment by CarsonLay** [comment]
I'm using openjdk-jdk-21-ga.
Sorry, I guess it is related to my compilation tool. It is not just a problem with hotspot. All compiled dylibs are missing __la_symbol_ptr, including libasyncProfiler.dylib or a HelloWorld code:

```C
// hello.c
#include <stdio.h>
char *kHelloPrefix = "Hello";
void say(char *prefix, char *name) {
    printf("%s, %s\n", prefix, name);
}
```

using clang
```bash
shao@shaodeMini tmp % clang -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```bash
shao@shaodeMini tmp % clang -fPIC -shared hello.c -o hello.dylib

shao@shaodeMini tmp % nm hello.dylib                                          
0000000000002000 D _kHelloPrefix
                 U _printf
0000000000000f60 T _say

shao@shaodeMini tmp % size -x -l -m hello.dylib                 
Segment __TEXT: 0x1000 (vmaddr 0x0 fileoff 0)
	Section __text: 0x2c (addr 0xf60 offset 3936)
	Section __stubs: 0x6 (addr 0xf8c offset 3980)
	Section __cstring: 0xe (addr 0xf92 offset 3986)
	Section __unwind_info: 0x58 (addr 0xfa0 offset 4000)
	total 0x98
Segment __DATA_CONST: 0x1000 (vmaddr 0x1000 fileoff 4096)
	Section __got: 0x8 (addr 0x1000 offset 4096)
	total 0x8
Segment __DATA: 0x1000 (vmaddr 0x2000 fileoff 8192)
	Section __data: 0x8 (addr 0x2000 offset 8192)
	total 0x8
Segment __LINKEDIT: 0x1000 (vmaddr 0x3000 fileoff 12288)
total 0x4000
```

Can't see __la_symbol_ptr

I know very little about compilers and need to learn more. Thank you for your answer.

**Comment by apangin** [comment]
Try `-mmacos-version-min=11`
This should generate lazy bindings.

I have no plans to support non-lazy bindings at this moment as long as async-profiler works fine with all major JDK distributions.

**Comment by CarsonLay** [comment]
Thank you for the great tip. When I added `-mmacos-version-min=11` to the compiler and linker options, the generated libjvm.dylib included `Section __la_symbol_ptr` and the flame graph was successfully generated.
