### ISSUE TITLE
Help interpreting snapshot

### ISSUE THREAD

**Issue by JohannesLichtenberger** [async-profiler/async-profiler#903]
[JsonShredderTest_testChicagoDescendantAxis_2024_03_10_235047.jfr.zip](https://github.com/async-profiler/async-profiler/files/14552043/JsonShredderTest_testChicagoDescendantAxis_2024_03_10_235047.jfr.zip)

![flamegraph](https://github.com/async-profiler/async-profiler/assets/1202851/5364ae47-f155-433b-8a2c-a66548905c2a)

Can you help me interpret what's the most pressing issue in my DBS project? I'm not sure if in the wall clock time flame graph I have appended the tiny portion hardly even visible means that's a problem, but I guess it's only showing that most ForkJoinPool threads are mostly parked.

I'm currently thinking about switching the `KeyValueLeafPage` implementation from using a byte array of byte arrays (for the slots + record-array, when deserialized) to an off-heap variant using the new `MemorySegment` class, but I'm not sure if that's even possible with my current approach (at least it's a bigger rewrite, I guess).

**Comment by apangin** [comment]
Thank you for your interest in async-profiler.

I'm happy to help you with profiler issues, however, this particular question looks more like a request for a free consulation on performance analysis of your project.

Furthermore, the attached recording is produced by IntelliJ IDEA profiler, which is a customized version of async-profiler that I unfortunatelly can't provide support for. Please contact JetBrains regarding IntelliJ profiler issues.

Feel free to edit the question to narrow it down to a specific async-profiler problem. In its current form, I'm inclined to close the issue as off-topic. Thanks.

**Comment by JohannesLichtenberger** [comment]
Oh sorry, in any case, it's a side project of mine since 11 years now and Open Source, so I'm getting a free IntelliJ license and I can't afford to spend more money on this (paying already for domains... plus my spare time ;)) or maybe I even would as I'm very interested in the topic

https://github.com/sirixdb/sirix
