### ISSUE TITLE
off cpu profiling

### ISSUE THREAD

**Issue by rustyrazorblade** [async-profiler/async-profiler#907]
I'm trying to figure out how to perform [off-cpu](https://brendangregg.com/offcpuanalysis.html) analysis using async-profiler, be it in combination with other tools or own its own.

In the past, I've used the offcputime utility in bcc-tools to trace off-cpu events, but since it doesn't capture the java stacks, it doesn't give me a complete picture.  I'm not sure if there's a way to take the results from that and use async-profiler to match up the java frames, or if I should just use async-profiler and trace each of the kprobes.   I'd like to have all off-cpu activity on a single graph ideally, so I'm hoping to avoid generating separate graphs for each kprobe.  

Any advice is appreciated!

**Comment by apangin** [comment]
Async-profiler does not currently support multiple kprobes simultaneously. Which kprobes would you like to profile?

As to off-cpu profiling, doesn't `wall` mode work for you?

**Comment by rustyrazorblade** [comment]
The issue with using wall clock time is that it includes time spent running user code rather than just the time CPU is spent waiting on I/O or other areas.  Here's an example of using offcputime with folded stacks + brenden gregg's flamegraph.pl:

```
offcputime -f -p $(cassandra-pid) 60 > offcputime3.txt
flamegraph.pl --color=io --title="Off-CPU Time Flame Graph" --countname=us < offcputime3.txt > offcputime.svg
```

Screenshot of the flame graph:

![offcputime](https://github.com/async-profiler/async-profiler/assets/337872/143f5ada-b889-4f16-926e-78911018bb84)

My goal is to be able to get the same flamegraph but with actual data instead of `Missed User Stack`.  Unfortunately I don't think i can use the stacks generated from offcputime, or maybe I'm not providing the right options.  Here's a sample from the output which leads me to believe there's no way to match up the frames:

```
Native-Transpor;[unknown];asm_sysvec_reschedule_ipi;sysvec_reschedule_ipi;irqentry_exit;irqentry_exit_to_user_mode;exit_to_user_mode_prepare;exit_to_user_mode_loop;schedule;finish_task_switch.isra.0 5
```

Looking at what's generated with async-profiler, when I run async-profiler with `-e wall`, I found myself a bit lost in the sea of stack traces.  

<img width="1466" alt="image" src="https://github.com/async-profiler/async-profiler/assets/337872/9f977d51-41ae-4c03-8497-4b8a1fa791dd">

Clearly I need to filter some of them out.  I'm thinking I could use the information I have from `offcputime` and pass the system calls I care about to `-I` to only include those stacks, that will probably get me where I need to go.  Scripting something that takes offcputime output, extracts the system calls of interest then builds a flamegraph command for me could be one option.  I can share that one it's done if it looks like that's the least-friction path to getting what I'm after.

Do you think this is a reasonable approach?  I don't know enough about some of the nuance here to quickly judge this idea.

**Comment by apangin** [comment]
> The issue with using wall clock time is that it includes time spent running user code rather than just the time CPU is spent waiting on I/O or other areas.

Wall clock profile includes both. When JFR output format is used, each wall clock sample is attributed with a thread state: `THREAD_RUNNABLE` or `THREAD_SLEEPING`. You can then use `jfr2flame` converter to build a flame graph from only `runnable` states or only from `sleeping` states, e.g.:
```
java -cp converter.jar jfr2flame --state sleeping profile.jfr flame.html
```

> My goal is to be able to get the same flamegraph but with actual data instead of Missed User Stack.

You can collect a similar flame graph with the following command:
```
sudo asprof -e kprobe:schedule -i 2 --cstack dwarf -f profile.html <pid>
```

> I'm thinking I could use the information I have from offcputime and pass the system calls I care about to -I to only include those stacks

This will not work, since a wall clock profile does not include kernel stacks.

**Comment by rustyrazorblade** [comment]
Hmm.. I'm trying this now, unfortunately I'm being bit by this:

```
[WARN] perf_event_open for TID 4256 failed: Permission denied
[WARN] perf_event_open for TID 4292 failed: Permission denied
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'
```

I'm not in a restricted mode:

```
root@cassandra0:~# cat /proc/sys/kernel/perf_event_paranoid
1
```

I'm also not running in a docker container, this is an Ubuntu image on EC2.

When I add `--fdtransfer` I get this error:

```
[WARN] perf_event_open for TID 4292 failed: Bad address
[ERROR] Perf events unavailable
```

I'll try setting up a build from source to see if there's a different result.

**Comment by rustyrazorblade** [comment]
Hmm... unfortunately no luck using the latest code.  I've tried using --all-user and --fdtransfer as well, but neither of those work either.  When using --fdtransfer I get a different error:

```
[WARN] perf_event_open for TID 9751 failed: Bad address
[ERROR] Perf events unavailable
```

I added some debugging output to perfEvents_linux.cpp and see that the call to `fd = syscall(__NR_perf_event_open, &attr, tid, -1, -1, 0);` is erroring, so I'm digging into that.  

I ran the program again using strace, and I'm looking at this output:

```
readlink("/proc", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
readlink("/proc/self", "10587", 1023)   = 5
readlink("/proc/10587", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
readlink("/proc/10587/exe", "/usr/local/ap/bin/asprof", 1023) = 24
readlink("/usr", 0x7fffe8f1ad00, 1023)  = -1 EINVAL (Invalid argument)
readlink("/usr/local", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
readlink("/usr/local/ap", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
readlink("/usr/local/ap/bin", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
readlink("/usr/local/ap/bin/asprof", 0x7fffe8f1ad00, 1023) = -1 EINVAL (Invalid argument)
newfstatat(AT_FDCWD, "/usr/local/ap/bin/../lib/libasyncProfiler.so", {st_mode=S_IFREG|0775, st_size=389792, ...}, 0) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x79809d354a10) = 10588
wait4(10588, [{WIFEXITED(s) && WEXITSTATUS(s) == 200}], 0, NULL) = 10588
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=10588, si_uid=0, si_status=200, si_utime=0, si_stime=0} ---
openat(AT_FDCWD, "/tmp/asprof-log.10587.9940", O_RDONLY) = 3
read(3, "[WARN] syscall\n[WARN] perf_event"..., 8192) = 5026
write(2, "[WARN] syscall\n[WARN] perf_event"..., 5026[WARN] syscall
```

It looks to me like the syscall to `perf_event_open` is called [here](https://github.com/async-profiler/async-profiler/blob/master/src/perfEvents_linux.cpp#L573C22-L573C42) from the Java process.  I'm making this assumption because I don't see the call in the strace output, and I see that asprof is reading from a file at `/tmp/asprof-log*.`

As a sanity check, I've verified I'm ablet to make perf calls, which I am as root:

```
root@cassandra0:/usr/local# perf record -F 99 -p $(cassandra-pid) sleep 10
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.045 MB perf.data (603 samples) ]
```

but they fail as a non-root user:

```
ubuntu@cassandra0:~/async-profiler$ perf record -F 99 -p $(cassandra-pid) sleep 10
Error:
Access to performance monitoring and observability operations is limited.
Consider adjusting /proc/sys/kernel/perf_event_paranoid setting to open
access to performance monitoring and observability operations for processes
without CAP_PERFMON, CAP_SYS_PTRACE or CAP_SYS_ADMIN Linux capability.
More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
perf_event_paranoid setting is -1:
  -1: Allow use of (almost) all events by all users
      Ignore mlock limit after perf_event_mlock_kb without CAP_IPC_LOCK
>= 0: Disallow raw and ftrace function tracepoint access
>= 1: Disallow CPU event access
>= 2: Disallow kernel profiling
To make the adjusted perf_event_paranoid setting permanent preserve it
in /etc/sysctl.conf (e.g. kernel.perf_event_paranoid = <setting>)
```

Even when `sysctl kernel.perf_event_paranoid` is set to -1:

```
ubuntu@cassandra0:~/async-profiler$ sysctl kernel.perf_event_paranoid
kernel.perf_event_paranoid = -1
```

I suspect if I'm able to figure out why `perf record` is unable to run, then this will be able to run as well.

**Comment by rustyrazorblade** [comment]
OK, I've figured it out.  

I suspect you're not seeing this issue because you're using an older kernel than me - maybe older than 5.8?  From https://man7.org/linux/man-pages/man7/capabilities.7.html

```
CAP_PERFMON (since Linux 5.8)
               Employ various performance-monitoring mechanisms,
               including:
 
               •  call [perf_event_open(2)](https://man7.org/linux/man-pages/man2/perf_event_open.2.html);
               •  employ various BPF operations that have performance
                  implications.
 
               This capability was added in Linux 5.8 to separate out
               performance monitoring functionality from the overloaded
               CAP_SYS_ADMIN capability.  See also the kernel source file
               Documentation/admin-guide/perf-security.rst.
```


Once I do the following:

```
setcap "cap_perfmon,cap_sys_ptrace,cap_syslog=ep" /usr/lib/jvm/java-11-openjdk-amd64/bin/java
```

and restart the java process, I'm able to run a profile:

<img width="1658" alt="image" src="https://github.com/async-profiler/async-profiler/assets/337872/a1c8a9b5-f096-4ab8-b85f-bfb0738cdeac">

I had opened #892 a while ago, but never actually got it to work, I believe this same issue is what got in the way.

Thank you for your help, and this project.  I've been able to track down several nasty performance issues with Apache Cassandra using it.

**Comment by apangin** [comment]
Right - in order to profile kprobes, not just asprof, but the Java process needs to run under `root`, or, as you correctly noticed, under a user with `CAP_PERFMON` capability.
