### ISSUE TITLE
Failed to inject profiler into <PID>

### ISSUE THREAD

**Issue by Slava96** [async-profiler/async-profiler#909]
Hello there!

I have a problem to run async-profiler on Java within Kubernetes pod. 
Docker image based on Alpine Linux and Java 17 and i send you a part of it related to async-profiler.

```
RUN mkdir /usr/local/async-profiler && wget -O /usr/local/async-profiler/async-profiler.tar.gz https://github.com/async-profiler/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-musl-x64.tar.gz &&\
 cd /usr/local/async-profiler &&\
 tar -xzvf async-profiler.tar.gz &&\
 rm -f /usr/local/async-profiler/async-profiler.tar.gz &&\
 cp -R async-profiler-2.9-linux-musl-x64/ /opt/async-profiler

RUN apk add libgcc libstdc++ libstdc++6
```
Under container file system, async-profiler stored at /opt/async-profiler directory.

In the same issues on this repository, i found that i will need to manually attach profiler to Java as agent with this command ` java -agentpath:/opt/async-profiler/build/libasyncProfiler.so=start,summary,flat -version`. I try this and get this error:

> Error occurred during initialization of VM
> Could not find agent library /opt/async-profiler/build/libasyncProfiler.so in absolute path, with error: /usr/glibc/lib/libgcc_s.so.1: version `GLIBC_2.0' not found (required by /opt/async-profiler/build/libasyncProfiler.so)

How can i fix this?

**Comment by apangin** [comment]
Please use version 3.0.
async-profiler 2.9 is no longer supported.

**Comment by Slava96** [comment]
Does async-profiler 3.0 have musl build?
Or default build successfully works with Alpine Linux on Kubernetes?

**Comment by apangin** [comment]
[async-profiler-3.0-linux-x64](https://github.com/async-profiler/async-profiler/releases/download/v3.0/async-profiler-3.0-linux-x64.tar.gz) should work on Alpine, too.
