### ISSUE TITLE
`-agentpath` mode consumes more code cache memory

### ISSUE THREAD

**Issue by indygreg** [async-profiler/async-profiler#914]
I'm using async-profiler 3.0 against Corretto OpenJDK 21.0.2.14.1.

When starting JVMs with `-agentpath:libasyncProfiler.so=start,event=itimer,event=alloc,interval=...,alloc=...,jfr,file=...`, I'm able to reliably observe a meaningful increase in code cache memory utilization.

JVMs are started with the aforementioned argument and then N seconds after startup I invoke `asprof stop` to stop the profiler and dump the output file.

JVMs have a segmented code cache and an increase is seen in both profiled and non-profiled nmethods code heaps.

Before async-profiler, the problematic JVM in question consumes ~220 MB of code cache after running for ~30 minutes, putting it very close to the default limit of 240 MB.

With this JVM, startup registration increases profiled and non-profiled nmethods memory from ~86 MB to ~116 MB each.

With and without `-agentpath`, we see non-profiled nmethods go to 100% eventually. But it is much faster with `-agentpath`.

With `-agentpath`, profiled nmethods goes to 100% after a few minutes. Without `-agentpath` is only hits ~80% utilization.

Non nmethods memory is unaffected.

It certainly appears that attaching/recording on startup induces higher memory usage.

Is this behavior expected?

Do you have any guidance for the impact that async-profiler may have on code cache memory utilization? e.g. should we be setting aside a fixed amount of code cache memory when enabling async-profiler?

**Comment by indygreg** [comment]
Oh, I left out the key detail that invoking `asprof collect` without `-agentpath` doesn't appear to incur a noticeable memory increase. The memory increase appears to either be isolated to use of async-profiler with `-agentpath` or the act of attaching async-profiler early in the JVM's lifetime. I'm still attempting to isolate conditions to reproduce.

**Comment by apangin** [comment]
Yes, this is somewhat expected. When libasyncProfiler is loaded, either via `-agentpath` or on the first `asprof` invocation, it enables `-XX:+DebugNonSafepoints` flag which forces generation of additional debuginfo alongside the compiled code. Without this flag, profiler may incorrectly map instruction addresses to bytecode indices in the topmost frame thus making stack traces less inaccurate.

The earlier profiler is attached - the more methods are compiled with extra debuginfo, and the larger is the total size of compiled methods. You will likely observe a similar increase in CodeCache utilization, if you start JVM without profiler but with `-XX:+DebugNonSafepoints` enabled.

BTW, there is an intention to do the same for JFR, see [JDK-8307057](https://bugs.openjdk.org/browse/JDK-8307057).

Currently, there is no workaround other than increasing CodeCache capacity. What I can probably offer is to skip setting `DebugNonSafepoints` automatically when user explicitly disables it in the command line. However, as mentioned above, this will have a downside of producing inaccurate stack traces (at least, in their topmost inlined frames).

**Comment by indygreg** [comment]
Thank you for the quick and detailed reply!

I added `-XX:+DebugNonSafepoints` and the shape/behavior of code cache memory looks nearly identical to the async-profiler `-agentpath` scenario. So your intuition that this extra debuginfo is eating the memory appears spot on.

I'll leave this issue open in case you want it to track docs improvements or something. But from my perspective the issue is resolved.

Thanks again.

**Comment by apangin** [comment]
I pushed the fix to avoid modifying `DebugNonSafepoints` when it is set in the command line.
With this fix, adding `-XX:-DebugNonSafepoints` JVM argument will prevent async-profiler from consuming more CodeCache memory (for the price of less accurate stack traces).
