### ISSUE TITLE
Introduce filtering by CPU

### ISSUE THREAD

**Issue by w-kudla** [async-profiler/async-profiler#919]
There should be an option to collect stack traces only for chosen CPUs. It would drastically reduce the amount of work the profiler has to do and make analysis easier. 
This is not a made up use case; there's a whole industry where pinning a single thread to an isolated core is default optimization strategy.

**Comment by apangin** [comment]
This is the same issue as #481. There was an attempt to implement the feature in #486, however, the pull request was incomplete. If you wish, you may try to revive that PR or create a new one.
