### ISSUE TITLE
How can openjdk1.8 use async-profile -e alloc without installing debug symbols

### ISSUE THREAD

**Issue by linliaoy** [async-profiler/async-profiler#924]
I use debug symbols in production environment, so I can't turn on debug symbols. I would like to ask if there is any good way.  Can it be used [perf-map-agent](https://github.com/jvm-profiling-tools/perf-map-agent)  ？perf-map-agent also uses jvmti，Or is it possible to print all the mappings in the test environment 。jmap dump analysis file will have a good display, I don't know if it can be used for reference, I am still confused at present, want to achieve this condition

**Comment by apangin** [comment]
Which JDK distribution do you use?
Many popular OpenJDK distributions do not require separate debug symbol package; they support allocation profiling out of the box:
- [Amazon Corretto](https://aws.amazon.com/corretto/)
- [Liberica JDK](https://bell-sw.com/pages/downloads/#jdk-8-lts)
- [Azul Zulu](https://www.azul.com/downloads/?package=jdk#zulu)
- [AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot)

**Comment by linliaoy** [comment]
> Which JDK distribution do you use?
> Many popular OpenJDK distributions do not require separate debug symbol package; they support allocation profiling out of the box:

openjdk version "1.8.0_171"

**Comment by linliaoy** [comment]
[VMObjectAlloc](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#VMObjectAlloc) can_generate_vm_object_alloc_events Why can only isOpenJ9 be enabled？

**Comment by linliaoy** [comment]
See the code can get AsyncGetCallTrace symbolic address, I have an idea to get jni AllocObject function symbolic address to trace, or at this time all the symbolic address output

**Comment by apangin** [comment]
Sorry, my question was about distribution (or vendor), not just about the version.
You can obtain it with `java -XshowSettings:properties -version`

As mentioned above, you can do allocation profiling on many OpenJDK 8 distributions without installing debug symbols. I don't think anything should be changed in this regard.

**Comment by linliaoy** [comment]
> Which JDK distribution do you use? Many popular OpenJDK distributions do not require separate debug symbol package; they support allocation profiling out of the box:
> 
> * [Amazon Corretto](https://aws.amazon.com/corretto/)
> * [Liberica JDK](https://bell-sw.com/pages/downloads/#jdk-8-lts)
> * [Azul Zulu](https://www.azul.com/downloads/?package=jdk#zulu)
> * [AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot)


The provided jdk contains debug symbols. Will it affect the performance and security of the production environment

**Comment by linliaoy** [comment]
> Sorry, my question was about distribution (or vendor), not just about the version. You can obtain it with `java -XshowSettings:properties -version`
> 
> As mentioned above, you can do allocation profiling on many OpenJDK 8 distributions without installing debug symbols. I don't think anything should be changed in this regard.


java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.version = 1.8.0_171

**Comment by linliaoy** [comment]
[vmtrace](https://github.com/odnoklassniki/jvmti-tools/blob/master/vmtrace/vmtrace.cpp)
I found that you obtained symbols based on jvmti implementation. I don't know whether the symbols started by the same jdk in multiple Pods are the same. I remember that the linux kernel can be reused

**Comment by apangin** [comment]
> The provided jdk contains debug symbols. Will it affect the performance and security of the production environment

Symbol table is just a simple table that maps function names to addresses and vice versa. It has no impact on security or runtime performance.

> java.vendor = Oracle Corporation
> java.vendor.url = http://java.oracle.com/
> java.version = 1.8.0_171

This JDK version is compiled with symbols included. You don't need to install anything additional - async-profiler should work fine with it out of the box.

**Comment by linliaoy** [comment]
I reported an error when using  
“./asprof -e alloc --alloc 500  -d 60 -f profile.html 1 ” 
or 
“./asprof -e alloc  -d 60 -f profile.html 1”

error：
    [WARN] Install JVM debug symbols to improve profile accuracy
   [ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?

**Comment by linliaoy** [comment]
I looked at the hotpot source code and found that the build version b11 I used did not have jvm tracing. The jvm tracing AllocTracer::send_allocation_in_new_tlab_event came after b95

**Comment by apangin** [comment]
I verified that async-profiler 3.0 works fine with Oracle JDK 1.8.0_171.
So the problem must be somewhere else.

Please check the output of the following commands:
```
nm JAVA_HOME/jre/lib/amd64/server/libjvm.so | grep AllocTracer
```
and
```
grep asyncProfiler /proc/PID/maps
```
where `JAVA_HOME` is the JDK directory and `PID` is the process ID of the Java application.

**Comment by linliaoy** [comment]
> grep asyncProfiler /proc/PID/maps

7fbe63072000-7fbe630ba000 r-xp 00000000 fd:10 4457358                    /async-profile/build/lib/libasyncProfiler.so
7fbe630ba000-7fbe632ba000 ---p 00048000 fd:10 4457358                    /async-profile/build/lib/libasyncProfiler.so
7fbe632ba000-7fbe632bb000 r--p 00048000 fd:10 4457358                    /async-profile/build/lib/libasyncProfiler.so
7fbe632bb000-7fbe632bc000 rw-p 00049000 fd:10 4457358                    /async-profile/build/lib/libasyncProfiler.so

**Comment by linliaoy** [comment]
Thank you. I use the docker jdk openjdk:8u171-jdk-slim. Maybe I need to study how to make this image and find out how to add symbols without affecting the current package size.

**Comment by linliaoy** [comment]
[native-debug-symbols](https://hg.openjdk.org/jdk/jdk11/raw-file/tip/doc/building.html#native-debug-symbols)
I have found that debug symbols can be used in the mode of external and zipped. I want to test whether the debug symbols of this jdk can be used before I put the debug file on it and remove it after use

**Comment by apangin** [comment]
OK, it makes sense now. `jdk-slim` image indeed has symbols stripped.
I suggest simply to use a different image with one of JDKs listed above. All mentioned vendors provide container images.
Another important reason to change docker image is to get important security updates. 8u171 is way too old.

**Comment by linliaoy** [comment]
attach and libasyncProfiler.so are not uninstalled after the -d time

**Comment by apangin** [comment]
I'm not sure what you mean by "attach is not uninstalled".
As to libasyncProfiler.so - it's not unloaded from the target process. This is by design and should not cause any problems.

**Comment by linliaoy** [comment]
When I am not using libasyncProfiler.so want to uninstall, is there a way

**Comment by apangin** [comment]
There is no need to "uninstall" profiler. It does not affect application and and does not consume resources when profiling is not running. You may safely remove profiler binaries from disk if you wish, but once the library is loaded in a Java process, it stays there until the process terminates.

**Comment by linliaoy** [comment]
Thank you. I'm closing this issue
