### ISSUE TITLE
Support debuginfod

### ISSUE THREAD

**Issue by mohe2015** [async-profiler/async-profiler#929]
Hi,

it seems like [debuginfod](https://sourceware.org/elfutils/Debuginfod.html) is becoming a popular way to distribute debug information and e.g. for Arch Linux it's the only easy way. It would be great if this would be supported. The easiest way would probably be to be able to read already cached debuginfod information or use `debuginfod-find`.

Kind regards
Moritz

**Comment by apangin** [comment]
Thank you for the proposal, it sounds interesting.
Async-profiler will hardly download anything on its own, but making use of cached debuginfod files definitely makes sense.

I will look into this sometime later, otherwise feel free to contribute a PR, if you wish.

**Comment by apangin** [comment]
Thanks to @krk, async-profiler can now load symbols form debuginfod cache.

**Comment by Trass3r** [comment]
> The easiest way would probably be to be able to read already cached debuginfod information or use debuginfod-find.

Ok so just for the record this has been implemented.
It won't automatically pull new symbols. (?!)

**Comment by apangin** [comment]
@Trass3r Correct. async-profiler now reads cached debuginfod symbols, but does not automatically pull new ones into the cache.
