### ISSUE TITLE
Why Are the Number of Threads and Thread IDs in the Profiler::instance()->threadFilter() Inaccurate?

### ISSUE THREAD

**Issue by 243300852** [async-profiler/async-profiler#930]
I have found that with a low number of concurrent service requests, it may not be possible to add threads to threadFilter.
I'm adding printing to this function <Java_one_profiler_AsyncProfiler_filterThread0> as follows. 
extern "C" DLLEXPORT void JNICALL

Java_one_profiler_AsyncProfiler_filterThread0(JNIEnv* env, jobject unused, jthread thread, jboolean enable) {

    int thread_id;
    if (thread == NULL) {
        thread_id = OS::threadId();
    } else if ((thread_id = VMThread::nativeThreadId(env, thread)) < 0) {
        return;
    }
    ThreadFilter* thread_filter = Profiler::instance()->threadFilter();
    if (enable) {
        std::cout << "Java_one_profiler_AsyncProfiler_filterThread0 add threadId " << thread_id << std::endl;
        thread_filter->add(thread_id);
    } else {
        std::cout << "Java_one_profiler_AsyncProfiler_filterThread0 reomve threadId " << thread_id << std::endl;
        thread_filter->remove(thread_id);
    }
    std::vector<int> tids;
    thread_filter->collect(tids);
    std::cout << "tids size " << tids.size() << " : ";
    for (int tid : tids) { 
        std::cout << tid << " ";
    }
    std::cout << std::endl;
}

The request and printing result is as follows，  I don't understand, why I requested once and the thread was not added but one was removed.

curl http://127.0.0.1:18080/benchmark-1/user/2
Java_one_profiler_AsyncProfiler_filterThread0 reomve threadId 1756803
tids size 0 :
{"id":"2","name":"test"}

curl http://127.0.0.1:18080/benchmark-1/user/2
Java_one_profiler_AsyncProfiler_filterThread0 reomve threadId 1756637
tids size 0 :
{"id":"2","name":"test"}

curl http://127.0.0.1:18080/benchmark-1/user/2
Java_one_profiler_AsyncProfiler_filterThread0 reomve threadId 1756653
tids size 0 :
{"id":"2","name":"test"}

**Comment by apangin** [comment]
This is not a question to async-profiler project.
`addThread`/`removeThread` methods are called by external software.
