### ISSUE TITLE
Attach process is crash when asprof

### ISSUE THREAD

**Issue by guoys** [async-profiler/async-profiler#938]
cmd: bin/asprof -d 30 -f /tmp/flamegraph.html 10086
result: attach process is crash
env info:
os:  3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
crash stack:
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fbb76cae329]
/lib64/libstdc++.so.6(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7fb963d68192]
/lib64/libstdc++.so.6(_ZNSt6locale5_ImplC1Em+0x1e3)[0x7fb963d685e3]
/lib64/libstdc++.so.6(+0x71555)[0x7fb963d69555]
/lib64/libpthread.so.0(+0x620b)[0x7fbb7741d20b]
/lib64/libstdc++.so.6(+0x715a1)[0x7fb963d695a1]
/lib64/libstdc++.so.6(_ZNSt6localeC2Ev+0x13)[0x7fb963d695e3]
/lib64/libstdc++.so.6(_ZNSt8ios_base4InitC2Ev+0xbc)[0x7fb963d6643c]
/data/apps/async-profiler/async-profiler-3.0-linux-x64/bin/../lib/libasyncProfiler.so(+0x4094a)[0x7fb96cdc694a]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x7fbb776429c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x7fbb7764759e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x7fbb776427d4]
/lib64/ld-linux-x86-64.so.2(+0x13b8b)[0x7fbb77646b8b]
/lib64/libdl.so.2(+0xfab)[0x7fbb76ffbfab]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x7fbb776427d4]
/lib64/libdl.so.2(+0x15ad)[0x7fbb76ffc5ad]
/lib64/libdl.so.2(dlopen+0x31)[0x7fbb76ffc041]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0x90e9e1)[0x7fbb765529e1]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0x77ddd1)[0x7fbb763c1dd1]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0x2f1c22)[0x7fbb75f35c22]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0xa7b9eb)[0x7fbb766bf9eb]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0xa7bcf1)[0x7fbb766bfcf1]
/data/applications/jdk1.8.0_202/jre/lib/amd64/server/libjvm.so(+0x90d8c2)[0x7fbb765518c2]
/lib64/libpthread.so.0(+0x7ea5)[0x7fbb7741eea5]
/lib64/libc.so.6(clone+0x6d)[0x7fbb76d2bb0d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 fd:10 268640367                          /data/applications/jdk1.8.0_202/bin/java
00600000-00601000 r--p 00000000 fd:10 268640367                          /data/applications/jdk1.8.0_202/bin/java
00601000-00602000 rw-p 00001000 fd:10 268640367                          /data/applications/jdk1.8.0_202/bin/java
00e77000-0f294000 rw-p 00000000 00:00 0                                  [heap]
5c0000000-6b8480000 rw-p 00000000 00:00 0 
6b8480000-715580000 ---p 00000000 00:00 0 
715580000-7bff00000 rw-p 00000000 00:00 0 
7bff00000-7c0000000 ---p 00000000 00:00 0 
7c0000000-7c0d40000 rw-p 00000000 00:00 0 
7c0d40000-800000000 ---p 00000000 00:00 0 
7fb76c000000-7fb76fd5a000 rw-p 00000000 00:00 0 
7fb76fd5a000-7fb770000000 ---p 00000000 00:00 0 
7fb774000000-7fb774594000 rw-p 00000000 00:00 0 
7fb774594000-7fb778000000 ---p 00000000 00:00 0 
7fb77c000000-7fb77fffd000 rw-p 00000000 00:00 0 
7fb77fffd000-7fb780000000 ---p 00000000 00:00 0 
7fb784000000-7fb78493a000 rw-p 00000000 00:00 0 

What should I do to make it work properly?

**Comment by apangin** [comment]
This seems to be exactly the same problem as in #793.
Do you use CentOS 7?
Please provide a minimal test case that I can use to reproduce the issue.

**Comment by guoys** [comment]
> This seems to be exactly the same problem as in #793. Do you use CentOS 7? Please provide a minimal test case that I can use to reproduce the issue.
Thanks for your replay.  Yes, it is CenOS7.   I don't know the exact case that reproduces it, but I've used the “-agentpath:” method with success.

**Comment by guoys** [comment]
> This seems to be exactly the same problem as in #793. Do you use CentOS 7? Please provide a minimal test case that I can use to reproduce the issue.

Thanks for your replay. Yes, it is CentOS7. I don't know the exact case that reproduces it, but I've used the “-agentpath:” method with success.

**Comment by apangin** [comment]
Thank you for the confirmation.
I'll be happy to know more about the exact JDK distribution used, the exact libstdc++ version and the type of an application that crashes. So far, I was not able to reproduce the issue myself.
In any case, the problem should go away once #872 is implemented.
