### ISSUE TITLE
Cannot use BPF with asprof

### ISSUE THREAD

**Issue by rus-99-pk** [async-profiler/async-profiler#941]
Hello!

I updated profiler from **profiler-bpf.sh** to **asprof**.

Early i used BPF-daemon with option `--fdtransfer2 bpf-profiler/bpf-daemon/bpf.socket`:
```bash
bpf-profiler/async-profiler/profiler-bpf.sh start -e bpf -f bpf-profiler/async-profiler/reports/profile-%t.jfr --fdtransfer2 bpf-profiler/bpf-daemon/bpf.socket -i 1 --chunktime 1m -o jfr --sched --loop 1h 19889
```

And now i try to run the same command with **asprof**, but i get error like:
```bash
async-profiler/bin/asprof start -e bpf -f async-profiler/profile-%t.jfr --fdtransfer2 bpf-profiler/bpf-daemon/bpf.socket -i 1 --chunktime 1m -o jfr --sched --loop 1h 19889
Unrecognized option: --fdtransfer2

async-profiler/bin/asprof start -e bpf -f async-profiler/profile-%t.jfr --fdtransfer bpf-profiler/bpf-daemon/bpf.socket -i 1 --chunktime 1m -o jfr --sched --loop 1h 19889
Unrecognized option: bpf-profiler/bpf-daemon/bpf.socket
```

Can you help me, what's wrong here?

**Comment by apangin** [comment]
Presumably, you used some third partly fork of async-profiler.
Original version never had `--fdtransfer2` option, and `profiler-bpf.sh` never existed in its source base.

**Comment by rus-99-pk** [comment]
> Original version never had --fdtransfer2 option, and profiler-bpf.sh never existed in its source base.

We used **bpfclient** branch for it.

**Comment by apangin** [comment]
There is no `--fdtransfer2` option in `bpfclient` branch either.

**Comment by rus-99-pk** [comment]
Ok, thank you very much!
I understood it.

But my question is still opened: can i use Profiler with BPF daemon, through BPF-socket?

**Comment by apangin** [comment]
What BFP daemon do you mean? Mainline async-profiler does not support eBPF.

**Comment by rus-99-pk** [comment]
> Mainline async-profiler does not support eBPF

Ok. As i understand it, **bpfclient** branch supports this feature?

**Comment by apangin** [comment]
`bpfclient` branch is to demonstrate the concept of _BPF-assisted profiling_. It is intended to work in conjunction with the [BPF program](https://github.com/odnoklassniki/async-profiler-bpf) attached to the selected perf_events.

Don't expect it to be the complete production ready solution. However, you may use it as a reference to implement your own BPF-assisted profiler.

**Comment by rus-99-pk** [comment]
Thank you!

One more question - how can i convert JFR to HeatMap with **converter.jar** from **main** branch of this repo?

I converted it using **converter.jar** from [Artyomcool](https://github.com/Artyomcool/async-profiler/tree/single-page-heatmap) repo early.
![изображение](https://github.com/async-profiler/async-profiler/assets/93255418/92d08686-ffc4-4e14-ac7b-c8bfe43318e6)

Then i tried to convert it to HeatMap using **converter.jar** from **asprof**, but it doesn't have this format.
![изображение](https://github.com/async-profiler/async-profiler/assets/93255418/5fd77390-d51c-4681-8843-1ec86b5b3ce3)

When i try to convert JFR created **asprof**, using **converter.jar* from [Artyomcool](https://github.com/Artyomcool/async-profiler/tree/single-page-heatmap), then get an empty HTML-file without **HeatMap**/**FlameGraph**.

How to live now?

**Comment by Artyomcool** [comment]
@apangin I think we can already say that we working on integrating heatmap feature into the main repo. There were some circumstances preventing us to do it earlier, but now it is only matter of time.

**Comment by apangin** [comment]
Closing the question as answered.
Feel free to submit a new issue if you have further questions.
