### ISSUE TITLE
Why'live' option is only supported on OpenJDK 11+, why JDK8 is not supported, is it a JDK limitation or async-profiler implementation limitation?

### ISSUE THREAD

**Issue by 243300852** [async-profiler/async-profiler#942]
Why'live' option is only supported on OpenJDK 11+, why JDK8 is not supported, is it a JDK limitation or async-profiler implementation limitation?

**Comment by apangin** [comment]
For the live object profiling, async-profiler relies on the JVM TI functionality that has appeared in JDK 11.
