### ISSUE TITLE
Fix broken JFR is possible?

### ISSUE THREAD

**Issue by rus-99-pk** [async-profiler/async-profiler#945]
Hello!

I configured Async-profiler, but JVM stucks while the application was running.

At the same time, JFR was apparently written, but after rebooting the JVM the file did not close as expected, and ultimately an error occurs when opening the file with JMC:
`org.openjdk.jmc.flightrecorder.internal.InvalidJfrFileException: No readable chunks in recording`

Can i close JFR with a specific sequence of bytes so that you can open it? Noticed that it have a starting and ending byte sequence.

**Example:**
At the start of the file:
![изображение](https://github.com/async-profiler/async-profiler/assets/93255418/feb0ff04-318e-43c7-8a21-ba4eb81f3066)

In the end:
![изображение](https://github.com/async-profiler/async-profiler/assets/93255418/31749b53-27c8-4da4-b50c-3dc8d0e46052)

I also found this thing ([split.jar](http://hirt.se/blog/?p=663)), but it does not work with current JFR (from asprof). Probably outdated.

**Comment by apangin** [comment]
Thank you for providing the file.
Unfortunately, this recording is not recoverable.

JFR recordings consist of a series of chunks. Each chunk is self-contained: it can be parsed independently of other chunks. If some chunk is incomplete or corrupted, it should be still possible to recover data from other chunks. In your case, however, the file includes only one incomplete chunk.

Chunk header starts with `FLR\0` (`0x46 0x4C 0x52 0x00`) - you may try to find this sequence in a recording. In your file, it occurs only once in the beginning. Also, the chunk length field in your recording has the value `0x40 0x00 0x00 0x00` which is a placeholder for an incomplete chunk.

Normal JFR chunk contains:
 - Metadata
 - Events
 - One or more constant pools

Constant pools hold all the symbolic information, such as method names, class names, stack traces, etc. Events usually contain numeric references into the constant pool. Even though there can be multiple constant pools in a chunk, async-profiler writes only one constant pool at the end of a chunk. So, your recording only has metadata and events, but no constant pools, therefore, it's impossible to decode numeric IDs in the events.

Async-profiler has two options to control chunk rotation:
 - `chunktime` specifies duration of each chunk;
 - `chunksize` determines a threshold in bytes when a chunk is flushed.

For example, `--chunktime 5m --chunksize 10m` forces async-profiler to record a new chunk every 5 minutes or every 10 megabytes of events, whichever happens earlier. With these options, even if JVM crashes, you'll be able to parse JFR recordings up to the last 5 minutes.

**Comment by apangin** [comment]
> how did you get these values?

I'm not sure what you mean. These are from the beginning of the file you've sent to me:
<img width="519" alt="jfr" src="https://github.com/async-profiler/async-profiler/assets/1749416/0dffd764-1201-4c63-af29-57cd3d0ee1ac">

**Comment by apangin** [comment]
Closing the issue as answered. Feel free to start a new [discussion](https://github.com/async-profiler/async-profiler/discussions) if you have further questions.
