### ISSUE TITLE
Add an asprof argument to specify the path of libasyncProfier.so in the container

### ISSUE THREAD

**Issue by yanglong1010** [async-profiler/async-profiler#955]
### Describe the feature

Hi, in 2.9 and bellow, there is an argument `--lib path` in `profiler.sh` to specify the path of libasyncProfier.so in the container.
But 3.0 and above, this argument is missing. I think this argument is necessary.

### Use Case

```bash
asprof -e cpu --libpath /tmp/libasyncProfiler.so 1234
```

### Proposed Solution

Add the argument back.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by apangin** [comment]
The plan is to make `asprof` automatically provide `libasyncProfier.so` to the process inside a container - in this case, the option will be redundant.
However, given that there is no timeline for this feature, and since adding `--libpath` is straightforward, I don't mind if you add this option.
