### ISSUE TITLE
`jfr2flame` can't properly filter thread states with `jfrsync` enabled.

### ISSUE THREAD

**Issue by shirolimit** [async-profiler/async-profiler#959]
### Describe the bug

`jfr2sync` can't properly convert JFRs containing both `cpu` and `wall` events when `jfrsync` is enabled:
- `--state DEFAULT` results in a flamegraph built from all the execution samples in the JFR
- `--state RUNNABLE,SLEEPING` results in an empty flamegraph.

I tried investigating the problem and found the following.

When capturing `cpu` and `wall` events simultaneously `async-profiler` differentiate them based on the `jdk.types.ThreadState` values. It seems that when `jfrsync` option is enabled `jdk.types.ThreadState` have different values than those enforced by `async-profiler`.

`jdk.types.ThreadState` for JFR profile w/o `jfrsync` enabled:
```
0=STATE_DEFAULT
1=STATE_RUNNABLE
2=STATE_SLEEPING
```
These values align with `async-profiler` constants defined in https://github.com/async-profiler/async-profiler/blob/6207d5dc865d9acdd8bfd8944177775d021f992c/src/os.h#L22-L26

`jdk.types.ThreadState` for JFR profile with `jfrsync` enabled:
```
0=STATE_NEW
225=STATE_SLEEPING
401=STATE_IN_OBJECT_WAIT
417=STATE_IN_OBJECT_WAIT_TIMED
657=STATE_PARKED
673=STATE_PARKED_TIMED
1025=STATE_BLOCKED_ON_MONITOR_ENTER
2=STATE_TERMINATED
5=STATE_RUNNABLE
```
Which probably correspond to JVMTI thread states.

I suspect that `jfr2flame` can't find some of the states (i.e. `DEFAULT`) and get wrong values for `RUNNABLE` and `SLEEPING`.

### Expected vs. actual behavior

**Expected behaviour**

`jfr2flame` produces CPU flamegraph with `--state DEFAULT` and WALL flamegraph with `--state RUNNABLE,SLEEPING` when `jfrsync` option is enabled.

**Actual behaviour**

WALL flamegraph is empty, CPU flamegraph is not correct and contain WALL samlpes.

### Reproduction Steps

Capture a profile using the following command:
```bash
asprof collect -e cpu,wall -d 15 -o jfr --jfrsync profile -f ap-jfrsync.jfr <pid>
```

Convert results JFR to flamegraphs using the following command:
```bash
java -cp converter.jar jfr2flame --state RUNNABLE,SLEEPING ap-jfrsync.jfr wall.html
java -cp converter.jar jfr2flame --state DEFAULT ap-jfrsync.jfr cpu.html
```

### Async-profiler version

2.10,3.0

### Environment details

JDK version:
```
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
```

**Comment by apangin** [comment]
Thank you for the report. I pushed the fix.

Note that converter command became much simpler in recent updates:
```
jfrconv --cpu ap-jfrsync.jfr cpu.html
jfrconv --wall ap-jfrsync.jfr wall.html
```
`--state` option is still supported, but can be also shortened:
```
jfrconv -s run,sleep ap-jfrsync.jfr wall.html
```

**Comment by shirolimit** [comment]
Works like a charm!
Thank you @apangin for such a quick fix and for the great tool!
