### ISSUE TITLE
"Profiler started" doesn't honor loglevel

### ISSUE THREAD

**Issue by geertn** [async-profiler/async-profiler#960]
### Describe the bug

In this PR https://github.com/async-profiler/async-profiler/pull/551 a loglevel argument was added with reasoning "This is particularly helpful if you're using async-profiler in production and where you don't want to clubber your output with not always relevant log information"

Using Grafana Profiles we are looking at enabling "Continuous profiling" in production. However when enabling the profiler using Grafana Alloy agent we get a large amount of "Profiling started" log messages in our applications.

Looking at the [source](https://github.com/async-profiler/async-profiler/blob/6207d5dc865d9acdd8bfd8944177775d021f992c/src/profiler.cpp#L1660C17-L1660C28) this and related messages seems to be written out to STDOUT without looking at loglevel.

We don't like to enable profiling in production if this means we can't control logging (and logging format) of our application. 

### Expected vs. actual behavior

"Profiling started" and related logs should honor the log level.

### Reproduction Steps

1. Start Java test program, eg `java -jar 'renaissance-gpl-0.15.0.jar' scrabble`
2. Attach asprof `./asprof -L error <pid>`
3. Observe application stdout:

```
====== scrabble (functional) [default], iteration 5 completed (573.007 ms) ======
====== scrabble (functional) [default], iteration 6 started ======
Profiling started
GC before operation: completed in 58.073 ms, heap usage 336.025 MB -> 78.046 MB.
====== scrabble (functional) [default], iteration 6 completed (448.292 ms) ======
====== scrabble (functional) [default], iteration 7 started ======
```

### Async-profiler version

3.0

**Comment by apangin** [comment]
Thank you for the report.
This is not a log message, but actual profiler output. E.g., this string is returned as a result of `execute` method; users of the profiler Java API may rely on this message.
The fix may not be that trivial. I'll see how to deal with this.

**Comment by krk** [comment]
Resolved in https://github.com/async-profiler/async-profiler/pull/986.
