### ISSUE TITLE
statement level profiling

### ISSUE THREAD

**Issue by robaho** [async-profiler/async-profiler#967]
### Describe the feature

It would be great if statement level profiling were possible (i.e. within a method).

### Use Case

Sometimes with a larger method with branches it is difficult to understand exactly where the time is being spent within a method for possible optimization.

The profiler in XCode allows this and I have found it very helpful at times.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by robaho** [comment]
Actually, I think this may already exist. If I distinguish stack frames by line number, I think this is doing what I need. I can get this when performing a capture using JFR - I am going to test if I get the same information if I have async profiler capture to jfr

**Comment by apangin** [comment]
When async-profiler uses jfr output format, it recods bci (bytecode indices) and line numbers when available.

You can then view recordings in JMC or IntelliJ IDEA. The latter will even annotate lines with the corresponding number of samples right in the code editor:

<img width="576" alt="idea-annotated-jfr" src="https://github.com/user-attachments/assets/e6bf979c-129f-4ef3-8945-4d6b8a7b8cab">

Also, you may use async-profiler's built-in JFR-to-FlameGraph converter with `--bci` or `--lines` options to produce a flamegraph with line numbers:

```
jfrconv --lines profiler.jfr profiler.html
```
<img width="547" alt="flame-lines" src="https://github.com/user-attachments/assets/974f8bfd-a203-42bc-8686-63b8567c4b8b">

**Comment by robaho** [comment]
Great. Thanks.
