### ISSUE TITLE
large of GC_active in the flamegraph

### ISSUE THREAD

**Issue by hokamc** [async-profiler/async-profiler#969]
### Describe the bug

<img width="566" alt="image" src="https://github.com/user-attachments/assets/b9c071b4-d4cc-40a9-af26-bc77807ad1a1">

We've installed the debug symbols from Zing, but the flamegraph still shows a lot of GC_active. Is there anything we can do to get a more detailed stacks?

### Expected vs. actual behavior

We expect to see the missing stacks.

### Reproduction Steps

Use Zing JDK, continuously trigger GC while profiling.

### Additional Information/Context

asprof -d 30 -f fg.html pid

### Async-profiler version

3.0

### Environment details

OS: Alibaba Cloud Linux 3 (Soaring Falcon)
ARCH: x86_64
JDK: zing-jdk17.0.0-24.02.100.0-5-x86_64

**Comment by apangin** [comment]
Thank you for the report.
It's a pecularity of Zing, and async-profiler can hardly do anything about it You may find some explanation in [this comment](https://github.com/async-profiler/async-profiler/issues/425#issuecomment-830058372).
In this case, async-profiler just reports what the JVM returns. Azul engineers should have more context on why this happens.

**Comment by hokamc** [comment]
Quote from azul engineers, no further action.
>Almost every time async profiler reports no java stack, Zing are in a compiler thread (with no java frames). As Zing has its own internal JVMTI DynamicCodeGenerated events, this couldn't be recognized by the profilers. 

> async-profiler is getting java frame name from OpenJDK/Oracle VM internals, but it can't get those from JVMTI's DynamicCodeGenerated events. Zing has its own internal representation for java compiled/interpreter methods info. This means async-profiler cannot recognize ZVM java frames method info and names only native frame, all Java frames are shown as 'unknown'.
