### ISSUE TITLE
lock profiling reports int[] as a monitor object

### ISSUE THREAD

**Issue by robaho** [async-profiler/async-profiler#972]
### Describe the bug

The lock profiling from the async profiler shows a strange number of int[] monitors.

I do not see this if I capture a JFR profile via JFR.

I reviewed the code, and I don't see any monitors at the reported line/method.

See screenshot:

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/79cc993e-625d-4ac4-870a-de6830907adb">

### Async-profiler version

3.0

### Environment details

OSX JDK24 Loom branch

**Comment by apangin** [comment]
This seems to be a [class initialization lock](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html#jvms-5.5).
Note that the JVM acquires initialization lock implicitly in the cases described in JVMS §5.5.

**Comment by robaho** [comment]
OK thanks. That makes sense. I think the reason I only see it with asprof is because I was starting with the agent so these class initializations were recorded, vs when I was capturing via JFR they had already occurred.
