### ISSUE TITLE
JVM crash with frame Profiler::getJavaTraceAsync

### ISSUE THREAD

**Issue by 243300852** [async-profiler/async-profiler#989]
### Describe the bug

Crash occurred while the service was running.
pkuuid:[GX19001243] agent:[GX19001243] ip:[10.218.132.158] organ:[86510000] source:[2]  version:[] bundle:[] mainThread:[2409061029518267] orderUuid:[2831878424238424066]  2024-09-06 INFO
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f89164312ac, pid=1, tid=0x00007f871bdfd700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libasyncProfiler.so+0x312ac]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int, StackContext*)+0x65c
#
# Core dump written. Default location: //core or core.1 (max size 5242880 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

[error occurred during error reporting , id 0xb]

[END] 2024/9/6 11:23:54

### Async-profiler version

2.10

### Environment details

NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0,31"
HOME_URL="https://openanolis.cn/"

**Comment by apangin** [comment]
Version 2.x is no lonter supported.
Please try an up-to-date version of async-profiler - preferably, from `master`.
The issue should have been fixed already.
